import type {
  AdvisoryEvidenceModel,
  Contradiction,
  ControlImprovementEntry,
  EvidenceChecklistItem,
  LeadershipDecision,
  MaterialFinding,
  PlausibleScenario,
  RiskRegisterEntry,
  RoadmapAction
} from '../evidence-model/types';
import type { ComprehensiveAnalyticalUniverse, ComprehensiveReviewerInput } from './types';

const reviewer = { name: 'Nadia Molefe', role: 'Independent review lead', organisation: 'MK Fraud Readiness', reviewDate: '2026-08-10' };

const baseFinding = (overrides: Partial<MaterialFinding>): MaterialFinding => ({
  id: 'F-ACCESS', title: 'Access review is not operating as a complete control', domainCode: 'D3', domainName: 'Operational Fraud Controls', questionCode: 'D3-Q04', questionPrompt: 'Access rights are reviewed and removed when no longer needed.', methodologyVersionId: 'fixture-v1', responseValue: 0, responseLabel: 'Not in place', responseOperationalMeaning: 'No control exists.', normalisedScore: 0, responseMeaning: 'No control exists', materialityClass: 'control_failure', selectionReasons: ['CRITICAL_GAP'], materialityScore: 98, isCriticalControl: true, isHardGate: true, gapClassification: 'critical', maturityCapStatus: 'capping', relatedCapRuleCodes: ['cap-access'], relatedCapRuleCode: 'cap-access', linkedExposureFactorCodes: ['EXP-06'], linkedScenarioTypes: ['privileged-access'], diagnosis: 'The recorded control position does not show a complete access-review rhythm.', whyItMatters: 'Excess access can allow activity to be initiated or concealed without timely challenge.', fraudMechanism: 'An inappropriate or stale access path is used to execute and conceal an unauthorised change.', likelyFinancialImpact: 'Unauthorised payments or value leakage.', likelyOperationalImpact: 'Investigation and containment are delayed.', expectedControlStandard: 'A complete, role-based access review is performed at the required frequency with exceptions evidenced.', evidenceToRequest: ['Current access review export and exception log'], recommendedControl: 'Implement a complete role-based access review with named approver, exception ageing and removal evidence.', accountableOwner: 'Chief Operating Officer', processOwner: 'IT and Operations', oversightFunction: 'Risk and Audit Committee', supportingFunctions: ['Human Resources', 'Information Security'], operatingFrequency: 'Quarterly', minimumEvidenceCharacteristics: ['Population is complete', 'Approvals and exceptions are traceable', 'Removals are evidenced'], dependencies: ['Identity inventory'], implementationDifficulty: 'Moderate', targetPeriod: '30 days', effectivenessMeasure: '100% of in-scope access reviewed with overdue exceptions escalated.', escalationThreshold: 'Any overdue privileged-access exception older than 30 days.', playbookSource: 'D3-Q04 fixture playbook', fallbackStatus: 'exact_question_playbook', selfAssessmentLimitation: 'Self-assessment only; no operating evidence was examined.', ...overrides });

const findings: MaterialFinding[] = [
  baseFinding({}),
  baseFinding({ id: 'F-ALERT', title: 'Detection tuning is not evidenced on a fixed cycle', domainCode: 'D4', domainName: 'Fraud Detection Capability', questionCode: 'D4-Q02', questionPrompt: 'Detection rules are reviewed and tuned on a fixed cycle.', responseValue: 1, responseLabel: 'Initial / ad hoc', responseOperationalMeaning: 'Exists only informally or inconsistently.', normalisedScore: 20, responseMeaning: 'Exists only informally or inconsistently', materialityClass: 'control_gap', selectionReasons: ['MAJOR_GAP'], materialityScore: 76, isCriticalControl: false, isHardGate: false, gapClassification: 'major', maturityCapStatus: 'not_capping', relatedCapRuleCodes: [], relatedCapRuleCode: null, linkedExposureFactorCodes: ['EXP-07'], linkedScenarioTypes: ['detection-evasion'], diagnosis: 'Detection tuning is recorded as ad hoc.', whyItMatters: 'Static rules can lose relevance as fraud patterns change.', fraudMechanism: 'A changing pattern is not flagged by stale detection logic.', likelyFinancialImpact: 'Losses accumulate before detection.', likelyOperationalImpact: 'Alert queues become noisy and less trusted.', expectedControlStandard: 'Detection rules are reviewed, tuned and signed off on a fixed cycle.', evidenceToRequest: ['Detection tuning log and rule-change approvals'], recommendedControl: 'Introduce a fixed detection review cycle with documented tuning, testing and sign-off.', accountableOwner: 'Chief Risk Officer', processOwner: 'Fraud Operations', oversightFunction: 'Risk Committee', supportingFunctions: ['Data and Technology'], operatingFrequency: 'Monthly', minimumEvidenceCharacteristics: ['Rule inventory is complete', 'Changes are tested', 'Exceptions are signed off'], dependencies: ['Rule inventory'], implementationDifficulty: 'Moderate', targetPeriod: '60 days', effectivenessMeasure: 'All active rules reviewed monthly with stale-rule exceptions tracked.', escalationThreshold: 'Any high-risk rule without a current review record.', selfAssessmentLimitation: 'Self-assessment only; no operating evidence was examined.' }),
  baseFinding({ id: 'F-TRAIN', title: 'Fraud-awareness training is self-reported but not supported for the full population', domainCode: 'D9', domainName: 'Fraud Culture and Awareness', questionCode: 'D9-Q01', questionPrompt: 'Staff receive fraud-awareness training at induction and on a recurring cycle.', responseValue: 4, responseLabel: 'Consistently operating', responseOperationalMeaning: 'Operating consistently in practice.', normalisedScore: 80, responseMeaning: 'Operating consistently in practice', materialityClass: 'assurance_priority', selectionReasons: ['STRONG_AGGREGATE_MASKING_CRITICAL_WEAKNESS'], materialityScore: 54, isCriticalControl: false, isHardGate: false, gapClassification: 'none', maturityCapStatus: 'not_capping', relatedCapRuleCodes: [], relatedCapRuleCode: null, linkedExposureFactorCodes: [], linkedScenarioTypes: ['culture'], diagnosis: 'The recorded response is strong, but the complete training population is not evidenced.', whyItMatters: 'A strong self-report does not demonstrate complete, current or role-specific coverage.', fraudMechanism: 'Uninformed staff miss or fail to escalate a fraud signal.', likelyFinancialImpact: 'Preventable losses continue.', likelyOperationalImpact: 'Reporting and response quality varies by team.', expectedControlStandard: 'Induction and recurring training coverage is complete, current and role-specific.', evidenceToRequest: ['Training completion report and course coverage map'], recommendedControl: 'Maintain a complete training population, role mapping, completion exceptions and periodic effectiveness test.', accountableOwner: 'Chief People Officer', processOwner: 'People and Culture', oversightFunction: 'Risk Committee', supportingFunctions: ['Business Unit Leaders'], operatingFrequency: 'Quarterly', minimumEvidenceCharacteristics: ['Population reconciled', 'Course coverage mapped to roles', 'Exceptions are escalated'], dependencies: ['People roster'], implementationDifficulty: 'Low', targetPeriod: '90 days', effectivenessMeasure: '95%+ completion with all exceptions assigned and tested.', escalationThreshold: 'Any high-risk role not current on required training.', selfAssessmentLimitation: 'Strong self-report; no complete population evidence was examined.' })
];

const risk = (overrides: Partial<RiskRegisterEntry>): RiskRegisterEntry => ({
  id: 'RISK-ACCESS', title: 'Stale or excess access may enable unauthorised activity', cause: 'Access review is not evidenced as complete and timely.', riskEvent: 'A stale or excessive access path is used to execute or conceal unauthorised activity.', financialImpact: 'Unauthorised payments or value leakage.', operationalImpact: 'Containment and investigation are delayed.', legalRegulatoryImpact: 'Control deficiencies may require escalation under applicable obligations.', reputationalImpact: 'Stakeholder confidence may be reduced.', riskStatement: 'Because access review is not evidenced as complete and timely, there is a risk that a stale or excessive access path is used to execute or conceal unauthorised activity.', linkedFindingIds: ['F-ACCESS'], linkedQuestionCodes: ['D3-Q04'], linkedScenarioIds: ['SC-ACCESS'], affectedDomains: ['D3'], affectedDomain: 'D3', likelihood: 'High', likelihoodRationale: 'A hard-gate weakness and linked operational exposure support a High qualitative likelihood.', impact: 'High', impactRationale: 'High impact reflects the plausible consequence pathway and linked exposure evidence.', priority: 'Critical', currentControlPosition: 'Operational Controls: No control exists; self-assessment only.', requiredTreatment: 'Implement a complete role-based access review.', accountableExecutive: 'Chief Operating Officer', processOwner: 'IT and Operations', oversightFunction: 'Risk and Audit Committee', targetPeriod: '30 days', accountableOwner: 'Chief Operating Officer', targetDate: '30 days', effectivenessMeasure: '100% of in-scope access reviewed.', evidenceRefs: ['finding:F-ACCESS', 'question:D3-Q04'], assessmentConfidence: 'Self-assessment only, not independently verified', remainingLimitation: 'No document, interview, transaction sample or system evidence has been independently verified.', ...overrides });

const riskRegister: RiskRegisterEntry[] = [risk({}), risk({ id: 'RISK-ALERT', title: 'Stale detection logic may allow a changing pattern to persist', cause: 'Detection tuning is not evidenced on a fixed cycle.', riskEvent: 'A changing fraud pattern is not flagged by stale detection logic.', financialImpact: 'Losses accumulate before detection.', operationalImpact: 'Alert queues become noisy and less trusted.', linkedFindingIds: ['F-ALERT'], linkedQuestionCodes: ['D4-Q02'], linkedScenarioIds: ['SC-ALERT'], affectedDomains: ['D4'], affectedDomain: 'D4', likelihood: 'Moderate', impact: 'High', priority: 'High', targetPeriod: '60 days', evidenceRefs: ['finding:F-ALERT', 'question:D4-Q02'] }), risk({ id: 'RISK-TRAIN', title: 'Training coverage may not be complete for higher-risk roles', cause: 'Training coverage is strong by self-report but not evidenced for the full population.', riskEvent: 'Uninformed staff miss or fail to escalate a fraud signal.', financialImpact: 'Preventable losses continue.', operationalImpact: 'Reporting quality varies by team.', linkedFindingIds: ['F-TRAIN'], linkedQuestionCodes: ['D9-Q01'], linkedScenarioIds: ['SC-TRAIN'], affectedDomains: ['D9'], affectedDomain: 'D9', likelihood: 'Low', impact: 'Moderate', priority: 'Medium', targetPeriod: '90 days', evidenceRefs: ['finding:F-TRAIN', 'question:D9-Q01'] })];

const control = (finding: MaterialFinding): ControlImprovementEntry => ({ id: `CI-${finding.questionCode}`, linkedFindingId: finding.id, linkedRiskId: riskRegister.find((item) => item.linkedFindingIds.includes(finding.id))?.id ?? '', linkedRiskIds: riskRegister.filter((item) => item.linkedFindingIds.includes(finding.id)).map((item) => item.id), linkedQuestionCode: finding.questionCode, currentState: `${finding.responseMeaning}; self-assessed and not independently verified.`, targetState: finding.expectedControlStandard, controlObjective: `Demonstrate that ${finding.questionPrompt.toLowerCase()}`, controlDesign: finding.recommendedControl, accountableExecutive: finding.accountableOwner, processOwner: finding.processOwner, oversightFunction: finding.oversightFunction, accountableOwner: finding.processOwner, oversightOwner: finding.oversightFunction, supportingFunctions: finding.supportingFunctions, operatingFrequency: finding.operatingFrequency, completePopulationCoverage: 'Complete in-scope population reconciled to the source register.', evidenceRetained: finding.evidenceToRequest, requiredEvidence: finding.evidenceToRequest, minimumEvidenceCharacteristics: finding.minimumEvidenceCharacteristics, dependencies: finding.dependencies, implementationDependency: finding.dependencies.join('; '), implementationDifficulty: finding.implementationDifficulty, targetPeriod: finding.targetPeriod, effectivenessTest: finding.effectivenessMeasure, escalationThreshold: finding.escalationThreshold, evidenceRefs: [`finding:${finding.id}`, `question:${finding.questionCode}`] });

const evidenceChecklist: EvidenceChecklistItem[] = [
  { id: 'EVID-ACCESS', artefact: 'Current access review export and exception log', linkedFindingIds: ['F-ACCESS'], linkedRiskIds: ['RISK-ACCESS'], linkedQuestionCodes: ['D3-Q04'], linkedFindingId: 'F-ACCESS', linkedRiskId: 'RISK-ACCESS', likelyOwner: 'IT and Operations', provesWhat: 'Whether access rights are reviewed and removed when no longer needed across the complete in-scope population.', expectedRecency: 'Quarterly', requiredPopulation: 'Complete in-scope access population.', samplingExpectation: 'Review complete population where feasible; otherwise sample exceptions and overdue items.', minimumAcceptableCharacteristics: ['Population is complete', 'Approvals and exceptions are traceable', 'Removals are evidenced'], reviewStatus: 'Not yet requested', evidenceRef: 'evidence:EVID-ACCESS' },
  { id: 'EVID-ALERT', artefact: 'Detection tuning log and rule-change approvals', linkedFindingIds: ['F-ALERT'], linkedRiskIds: ['RISK-ALERT'], linkedQuestionCodes: ['D4-Q02'], linkedFindingId: 'F-ALERT', linkedRiskId: 'RISK-ALERT', likelyOwner: 'Fraud Operations', provesWhat: 'Whether detection rules are reviewed and tuned on a fixed cycle across the active rule population.', expectedRecency: 'Monthly', requiredPopulation: 'Complete active detection-rule population.', samplingExpectation: 'Review all high-risk rules and a documented sample of other rules.', minimumAcceptableCharacteristics: ['Rule inventory is complete', 'Changes are tested', 'Exceptions are signed off'], reviewStatus: 'Not yet requested', evidenceRef: 'evidence:EVID-ALERT' },
  { id: 'EVID-TRAIN', artefact: 'Training completion report and course coverage map', linkedFindingIds: ['F-TRAIN'], linkedRiskIds: ['RISK-TRAIN'], linkedQuestionCodes: ['D9-Q01'], linkedFindingId: 'F-TRAIN', linkedRiskId: 'RISK-TRAIN', likelyOwner: 'People and Culture', provesWhat: 'Whether induction and recurring fraud-awareness training covers the complete role population.', expectedRecency: 'Quarterly', requiredPopulation: 'Complete employee and contractor population in scope.', samplingExpectation: 'Reconcile population and exceptions; inspect role mapping and effectiveness test.', minimumAcceptableCharacteristics: ['Population reconciled', 'Course coverage mapped to roles', 'Exceptions are escalated'], reviewStatus: 'Not yet requested', evidenceRef: 'evidence:EVID-TRAIN' }
];

const scenarios: PlausibleScenario[] = [
  { id: 'SC-ACCESS', scenarioType: 'privileged-access', scenarioBasis: 'control_gap', title: 'Stale access is used to alter a value-bearing record and conceal the change', confirmedOperatingContext: ['Operational and digital access is material to the organisation.', 'Access review is recorded as not in place.'], entryPoint: 'A stale or excessive account remains active.', linkedControlWeaknesses: ['F-ACCESS'], fraudSequence: 'An unauthorised change is made and the audit trail is obscured or discovered late.', controlsExpected: ['Role-based access review', 'Exception escalation', 'Removal evidence'], concealmentMechanism: 'Activity is blended into ordinary operational changes.', whyControlsMayNotCatchIt: 'The complete population and exception process are not evidenced.', earlyWarningIndicators: ['Overdue access exceptions', 'Unusual change outside role pattern'], likelyImpact: ['Financial leakage', 'Delayed investigation'], financialImpact: 'Unauthorised payments or value leakage.', operationalImpact: 'Containment and investigation are delayed.', immediateContainment: 'Review privileged and high-risk access exceptions.', longerTermResponse: 'Implement a complete review and removal rhythm.', linkedFindingIds: ['F-ACCESS'], linkedQuestionCodes: ['D3-Q04'], linkedRiskIds: ['RISK-ACCESS'], linkedRiskId: 'RISK-ACCESS', evidenceRefs: ['evidence:EVID-ACCESS'], disclaimer: 'This is a plausible scenario, not an allegation, and is not evidence that an event occurred.' },
  { id: 'SC-ALERT', scenarioType: 'detection-evasion', scenarioBasis: 'control_gap', title: 'A changing fraud pattern is not flagged by stale detection rules', confirmedOperatingContext: ['Manual intervention and exception volume are material.', 'Detection tuning is recorded as ad hoc.'], entryPoint: 'A pattern changes after the last rule review.', linkedControlWeaknesses: ['F-ALERT'], fraudSequence: 'Activity continues below or outside stale thresholds until a manual review identifies it.', controlsExpected: ['Fixed review cycle', 'Rule testing', 'Exception reporting'], concealmentMechanism: 'Activity resembles normal volume or is split across channels.', whyControlsMayNotCatchIt: 'Rule inventory and review evidence are not current.', earlyWarningIndicators: ['Rising false negatives', 'Unreviewed high-risk rules'], likelyImpact: ['Accumulating loss', 'Loss of alert confidence'], financialImpact: 'Losses accumulate before detection.', operationalImpact: 'Alert queues become noisy and less trusted.', immediateContainment: 'Review high-risk rules and open detection exceptions.', longerTermResponse: 'Establish monthly tuning and sign-off.', linkedFindingIds: ['F-ALERT'], linkedQuestionCodes: ['D4-Q02'], linkedRiskIds: ['RISK-ALERT'], linkedRiskId: 'RISK-ALERT', evidenceRefs: ['evidence:EVID-ALERT'], disclaimer: 'This is a plausible scenario, not an allegation, and is not evidence that an event occurred.' },
  { id: 'SC-TRAIN', scenarioType: 'culture', scenarioBasis: 'assurance_validation', title: 'A role-specific signal is missed because training coverage is incomplete', confirmedOperatingContext: ['Training is self-reported as consistently operating.', 'Full population coverage is not evidenced.'], entryPoint: 'A higher-risk role receives outdated or no role-specific guidance.', linkedControlWeaknesses: ['F-TRAIN'], fraudSequence: 'A warning sign is not escalated or recorded promptly.', controlsExpected: ['Role mapping', 'Current training', 'Effectiveness test'], concealmentMechanism: 'The missed signal is treated as an ordinary exception.', whyControlsMayNotCatchIt: 'Coverage completeness has not been independently validated.', earlyWarningIndicators: ['Untrained high-risk roles', 'Repeated reporting errors'], likelyImpact: ['Preventable losses', 'Inconsistent escalation'], financialImpact: 'Preventable losses continue.', operationalImpact: 'Reporting quality varies by team.', immediateContainment: 'Reconcile high-risk role training status.', longerTermResponse: 'Maintain complete coverage and test effectiveness.', linkedFindingIds: ['F-TRAIN'], linkedQuestionCodes: ['D9-Q01'], linkedRiskIds: ['RISK-TRAIN'], linkedRiskId: 'RISK-TRAIN', evidenceRefs: ['evidence:EVID-TRAIN'], disclaimer: 'This is a plausible scenario, not an allegation, and is not evidence that an event occurred.' }
];

const contradictions: Contradiction[] = [{ id: 'CX-ACCESS', pattern: 'strong_domain_failed_critical_control', title: 'A blended position can mask a failed access control', drivingResponses: 'The overall position contains strong self-reported controls while access review is recorded as not in place.', whyItMatters: 'Aggregate strength should not be read as proof that a non-negotiable control operates.', falseComfortRisk: 'Leadership may rely on the aggregate score and miss the failed control.', whatLeadershipShouldVerify: 'Can current operating evidence demonstrate complete access review and removal?', fraudPathwayEnabled: 'The specific failed control is exploited while the aggregate score discourages deeper review.', linkedFindingIds: ['F-ACCESS'], linkedRiskId: 'RISK-ACCESS', evidenceRefs: ['finding:F-ACCESS', 'evidence:EVID-ACCESS'], materialityScore: 98 }];
const leadershipDecisions: LeadershipDecision[] = [{ id: 'DEC-ACCESS', decisionCategory: 'accountable_executive_mandate', decisionRequired: 'Mandate complete access review and exception closure.', evidenceDrivingIt: 'F-ACCESS · evidence:EVID-ACCESS', whyNow: 'Access is a critical control and the current position is not evidenced.', recommendedDecision: 'Approve accountable executive ownership, a 30-day first deliverable and escalation for overdue exceptions.', accountableExecutive: 'Chief Operating Officer', implementationOwner: 'IT and Operations', oversightFunction: 'Risk and Audit Committee', targetPeriod: '30 days', deadline: '30 days', consequenceOfDelay: 'Exposure remains unbounded and assurance stays limited.', immediateNextDeliverable: 'Complete population and exception log.', linkedFindingIds: ['F-ACCESS'], linkedRiskIds: ['RISK-ACCESS'], evidenceRefs: ['finding:F-ACCESS', 'risk:RISK-ACCESS', 'evidence:EVID-ACCESS'] }];
const roadmapActions: RoadmapAction[] = [
  { id: 'ACT-ACCESS-30', period: '30 days', domainCode: 'D3', domainName: 'Operational Fraud Controls', deliverable: 'Reconcile the complete access population and close or escalate overdue exceptions.', accountableExecutive: 'Chief Operating Officer', processOwner: 'IT and Operations', oversightFunction: 'Risk and Audit Committee', supportingFunctions: ['Human Resources'], linkedFindingIds: ['F-ACCESS'], linkedRiskIds: ['RISK-ACCESS'], dependencyIds: [], escalationThreshold: 'Any overdue privileged-access exception older than 30 days.', evidenceRefs: ['evidence:EVID-ACCESS'], accountableOwner: 'Chief Operating Officer', linkedFindingId: 'F-ACCESS', linkedRiskId: 'RISK-ACCESS', dependency: 'Identity inventory', implementationDifficulty: 'Moderate', successMeasure: '100% of in-scope access reviewed.', evidenceOfCompletion: 'Approved access review export, exception log and removal evidence.' },
  { id: 'ACT-ALERT-60', period: '60 days', domainCode: 'D4', domainName: 'Fraud Detection Capability', deliverable: 'Run the first fixed-cycle detection tuning review and evidence sign-off.', accountableExecutive: 'Chief Risk Officer', processOwner: 'Fraud Operations', oversightFunction: 'Risk Committee', supportingFunctions: ['Data and Technology'], linkedFindingIds: ['F-ALERT'], linkedRiskIds: ['RISK-ALERT'], dependencyIds: [], escalationThreshold: 'Any high-risk rule without a current review record.', evidenceRefs: ['evidence:EVID-ALERT'], accountableOwner: 'Chief Risk Officer', linkedFindingId: 'F-ALERT', linkedRiskId: 'RISK-ALERT', dependency: 'Rule inventory', implementationDifficulty: 'Moderate', successMeasure: 'All active rules reviewed monthly.', evidenceOfCompletion: 'Tuning log, test results and approvals.' },
  { id: 'ACT-TRAIN-90', period: '90 days', domainCode: 'D9', domainName: 'Fraud Culture and Awareness', deliverable: 'Reconcile role-based training coverage and test effectiveness for higher-risk roles.', accountableExecutive: 'Chief People Officer', processOwner: 'People and Culture', oversightFunction: 'Risk Committee', supportingFunctions: ['Business Unit Leaders'], linkedFindingIds: ['F-TRAIN'], linkedRiskIds: ['RISK-TRAIN'], dependencyIds: [], escalationThreshold: 'Any high-risk role not current on required training.', evidenceRefs: ['evidence:EVID-TRAIN'], accountableOwner: 'Chief People Officer', linkedFindingId: 'F-TRAIN', linkedRiskId: 'RISK-TRAIN', dependency: 'People roster', implementationDifficulty: 'Low', successMeasure: '95%+ completion with all exceptions assigned.', evidenceOfCompletion: 'Completion report, role map and effectiveness test.' }
];

const analytical: ComprehensiveAnalyticalUniverse = {
  evidenceModel: { materialFindings: findings, contradictions, scenarios, riskRegister, controlImprovements: findings.map(control), evidenceChecklist, leadershipDecisions, roadmapActions, functionalAgenda: [] },
  score: { overallScore: 61, calculatedMaturity: 'Developing', finalMaturity: 'Developing', exposureScore: 66, exposureBand: 'High', coveragePct: 100, nARatePct: 0, criticalGapCount: 1, majorGapCount: 1, capApplied: true, capReason: 'Critical access control condition recorded.', methodologyVersionId: 'fixture-v1' },
  organisationName: 'Harbourview Services (synthetic fixture)', assessmentReference: 'CMP-FIXTURE-001', generatedAt: '2026-08-10'
};

const baseReviewer = (evidenceReviews: ComprehensiveReviewerInput['evidenceReviews']): ComprehensiveReviewerInput => ({ reviewer, evidenceReviews, findingReviews: [], observations: [], managementDecisions: [{ id: 'MD-001', decision: 'Approve the access-review remediation mandate.', rationale: 'The control is critical and not evidenced.', linkedFindingIds: ['F-ACCESS'], linkedRiskIds: ['RISK-ACCESS'], owner: 'Chief Operating Officer', targetDate: '2026-09-09', status: 'OPEN', boardDecision: 'Board to note and track.' }], boardDecisions: ['Track unresolved evidence monthly.'], signOff: { signed: true, signedAt: '2026-08-10T12:00:00Z' } });

export const comprehensiveFixtures: Record<string, { label: string; analytical: ComprehensiveAnalyticalUniverse; reviewer: ComprehensiveReviewerInput }> = {
  weakOrganisationMeaningfulEvidence: { label: 'A. Weak organisation with meaningful evidence supplied', analytical, reviewer: baseReviewer([{ evidenceRef: 'evidence:EVID-ACCESS', evidenceExamined: ['Current access review export', 'Exception log'], validationStatus: 'VALIDATED_SUPPORTED', reviewerObservation: 'The reviewed population and exception trail support the stated remediation scope.', reviewerConfidence: 'HIGH' }, { evidenceRef: 'evidence:EVID-ALERT', evidenceExamined: ['Detection tuning log'], validationStatus: 'EVIDENCE_REVIEWED', reviewerObservation: 'A tuning record was examined, but the cycle is not yet consistently evidenced.', reviewerConfidence: 'MEDIUM' }]) },
  mixedControlContradiction: { label: 'B. Mixed control environment where evidence contradicts self-assessment', analytical, reviewer: { ...baseReviewer([{ evidenceRef: 'evidence:EVID-ACCESS', evidenceExamined: ['Access review export'], validationStatus: 'NOT_VALIDATED_INSUFFICIENT', reviewerObservation: 'The export did not reconcile to the complete population.', evidenceLimitation: 'The source population was incomplete.' }]), findingReviews: [{ findingId: 'F-ACCESS', evidenceRefs: ['evidence:EVID-ACCESS'], validationStatus: 'NOT_VALIDATED_INSUFFICIENT', reviewerObservation: 'The evidence does not support the recorded control position.', evidenceLimitation: 'Population completeness could not be established.', adjustedInterpretation: 'Retain the deterministic finding; do not describe the control as validated.', agreedOwner: 'Chief Operating Officer', agreedDueDate: '2026-09-09', managementResponse: 'Management will reconcile the source population.' }] } },
  strongSelfReportInsufficientEvidence: { label: 'C. Strong self-reported control but insufficient evidence', analytical, reviewer: baseReviewer([{ evidenceRef: 'evidence:EVID-TRAIN', evidenceExamined: ['Training summary'], validationStatus: 'NOT_VALIDATED_INSUFFICIENT', reviewerObservation: 'The summary is not enough to demonstrate complete role-based coverage.', evidenceLimitation: 'No reconciled employee and contractor population was supplied.' }]) },
  fullVisibilityNonSystemicCase: { label: 'D. Full visibility but non-systemic case', analytical, reviewer: { ...baseReviewer([{ evidenceRef: 'evidence:EVID-ACCESS', evidenceExamined: ['Access review export'], validationStatus: 'VALIDATED_SUPPORTED', reviewerObservation: 'The reviewed sample supports the specific case scope; no conclusion is made about unrelated populations.', reviewerConfidence: 'HIGH' }]), observations: [{ id: 'OBS-001', subject: 'Specific access exception', observation: 'The reviewed exception is isolated to the supplied case and is not treated as systemic without population evidence.', validationStatus: 'REVIEWER_JUDGEMENT', linkedEvidenceRefs: ['evidence:EVID-ACCESS'], linkedFindingIds: ['F-ACCESS'], reviewerName: reviewer.name, reviewDate: reviewer.reviewDate }] } }
};

