import type { OfficialResponseLabel } from '../response-labels';
import type { ImplementationDifficulty, TargetPeriod } from './types';

export interface AuthoritativeQuestionMapping {
  questionCode: string;
  prompt: string;
  domainCode: string;
  isCritical: boolean;
  isHardGate: boolean;
}

export interface QuestionControlPlaybook {
  questionCode: string;
  domainCode: string;
  controlObjective: string;
  expectedStandard: string;
  fraudMechanism: string;
  currentStateDiagnosis: (label: OfficialResponseLabel) => string;
  recommendedControlDesign: string;
  executiveAccountability: string;
  processOwnership: string;
  oversightFunction: string;
  supportingFunctions: string[];
  operatingFrequency: string;
  evidenceRequired: string[];
  minimumAcceptableEvidenceCharacteristics: string[];
  dependencies: string[];
  implementationDifficulty: ImplementationDifficulty;
  targetPeriod: TargetPeriod;
  effectivenessMeasure: string;
  escalationThreshold: string;
  relatedScenarioTypes: string[];
}

function diagnosis(control: string) {
  return (label: OfficialResponseLabel) =>
    `${control} was self-assessed as "${label.label}" (${label.operationalMeaning}; normalised score ${label.normalisedScore}/100). This is self-reported and requires the listed operating evidence before it can be treated as verified.`;
}

/**
 * V1.1 question copy verified against the immutable methodology seed/copy-polish source. The
 * registry lookup itself is by persisted question code, while the live finding always retains the
 * prompt persisted on the score trace so reports remain methodology-version traceable.
 */
export const AUTHORITATIVE_QUESTION_MAPPINGS: Record<string, AuthoritativeQuestionMapping> = {
  'D1-Q01': { questionCode: 'D1-Q01', domainCode: 'D1', isCritical: true, isHardGate: true, prompt: 'A named senior owner is accountable for fraud risk management and has authority to drive action.' },
  'D1-Q04': { questionCode: 'D1-Q04', domainCode: 'D1', isCritical: true, isHardGate: true, prompt: 'Management owns fraud risk, while internal audit or assurance functions provide independent review where they exist.' },
  'D3-Q03': { questionCode: 'D3-Q03', domainCode: 'D3', isCritical: true, isHardGate: true, prompt: 'Supplier onboarding includes checks on business information, ownership, banking details or other fraud-risk indicators.' },
  'D3-Q04': { questionCode: 'D3-Q04', domainCode: 'D3', isCritical: true, isHardGate: true, prompt: 'System and data access are granted based on role requirements and reviewed periodically.' },
  'D4-Q02': { questionCode: 'D4-Q02', domainCode: 'D4', isCritical: false, isHardGate: false, prompt: 'Exception reports or alerts highlighting unusual transactions or activities are generated and reviewed regularly.' },
  'D5-Q01': { questionCode: 'D5-Q01', domainCode: 'D5', isCritical: true, isHardGate: true, prompt: 'The organisation has a documented process for responding to suspected fraud incidents.' },
  'D5-Q05': { questionCode: 'D5-Q05', domainCode: 'D5', isCritical: true, isHardGate: true, prompt: 'Evidence linked to suspected fraud is identified, preserved and handled appropriately.' },
  'D6-Q01': { questionCode: 'D6-Q01', domainCode: 'D6', isCritical: true, isHardGate: false, prompt: 'The organisation provides a confidential or anonymous channel for reporting suspected fraud or misconduct.' },
  'D7-Q01': { questionCode: 'D7-Q01', domainCode: 'D7', isCritical: true, isHardGate: false, prompt: 'Suppliers, contractors or other third parties are subject to due diligence before being engaged.' },
  'D7-Q04': { questionCode: 'D7-Q04', domainCode: 'D7', isCritical: true, isHardGate: true, prompt: 'Supplier payment processes include checks to reduce invoice manipulation, fake vendors, bank-detail changes or vendor impersonation.' },
  'D8-Q02': { questionCode: 'D8-Q02', domainCode: 'D8', isCritical: true, isHardGate: true, prompt: 'Systems or digital platforms are monitored for suspicious activity such as unusual login, access, profile, transaction or account behaviour.' },
  'D8-Q04': { questionCode: 'D8-Q04', domainCode: 'D8', isCritical: true, isHardGate: true, prompt: 'Access to sensitive digital systems, administrator rights and confidential data is restricted and reviewed.' },
  'D8-Q05': { questionCode: 'D8-Q05', domainCode: 'D8', isCritical: false, isHardGate: false, prompt: 'Digital activity is monitored for misuse, unauthorised transactions, suspicious data changes or channel abuse.' },
  'D9-Q01': { questionCode: 'D9-Q01', domainCode: 'D9', isCritical: false, isHardGate: false, prompt: "Employees receive periodic training or guidance on fraud risks relevant to their roles and the organisation's operating environment." }
};

const PLAYBOOKS: Record<string, QuestionControlPlaybook> = {
  'D1-Q01': {
    questionCode: 'D1-Q01', domainCode: 'D1', controlObjective: 'Give one senior executive explicit authority and accountability for fraud-risk decisions.',
    expectedStandard: 'A named senior executive owns the fraud-risk programme, its budget, unresolved exceptions and reporting to the governing body.',
    fraudMechanism: 'Without an empowered owner, cross-functional fraud-control gaps remain unresolved because no one can allocate resources or compel action.',
    currentStateDiagnosis: diagnosis('Senior fraud-risk ownership'),
    recommendedControlDesign: 'The CEO must issue a dated fraud-risk accountability mandate naming one executive, delegated decision rights, budget authority, quarterly reporting obligations and a 30-day escalation route for overdue control actions; the company secretary retains approvals and quarterly packs.',
    executiveAccountability: 'CEO / Managing Director', processOwnership: 'Named fraud-risk executive', oversightFunction: 'Board / Audit Committee', supportingFunctions: ['Company Secretary', 'Risk', 'Finance'],
    operatingFrequency: 'Quarterly governance reporting; monthly overdue-action review', evidenceRequired: ['Signed executive accountability mandate', 'Last two fraud-risk governance packs', 'Overdue-action escalation log'],
    minimumAcceptableEvidenceCharacteristics: ['Names one accountable executive and decision rights', 'Shows decisions, owners and due dates', 'Shows escalation after 30 days overdue'], dependencies: ['Board or audit-committee reporting calendar'], implementationDifficulty: 'Low', targetPeriod: '30 days',
    effectivenessMeasure: '100% of material fraud actions have a funded owner and due date, with overdue items escalated within 30 days.', escalationThreshold: 'Any material control action without an owner or more than 30 days overdue.', relatedScenarioTypes: ['governance_accountability_failure']
  },
  'D1-Q04': {
    questionCode: 'D1-Q04', domainCode: 'D1', controlObjective: 'Separate management ownership of fraud risk from independent assurance over that ownership.',
    expectedStandard: 'Management designs and operates fraud controls; internal audit or another independent function periodically tests them and reports without assuming management responsibility.',
    fraudMechanism: 'When assurance owns the control it later reviews, gaps can be accepted or missed without an independent challenge.', currentStateDiagnosis: diagnosis('Management-versus-assurance role separation'),
    recommendedControlDesign: 'The CEO and audit-committee chair must approve a RACI that assigns control operation to management and risk owners, reserves independent testing and unrestricted reporting for internal audit or equivalent assurance, and requires annual conflict review; the company secretary retains the approved RACI and minutes.',
    executiveAccountability: 'CEO / Managing Director', processOwnership: 'Head of Risk and business control owners', oversightFunction: 'Audit Committee / Internal Audit', supportingFunctions: ['Company Secretary', 'Legal / Compliance'],
    operatingFrequency: 'Annual mandate review and quarterly exception reporting', evidenceRequired: ['Approved fraud-risk RACI', 'Internal audit charter or assurance mandate', 'Audit-committee minutes showing independent reporting'], minimumAcceptableEvidenceCharacteristics: ['Separates operation from testing for each key control', 'Gives assurance unrestricted reporting access', 'Records conflicts and recusals'], dependencies: ['Named management control owners', 'Independent assurance mandate'], implementationDifficulty: 'Moderate', targetPeriod: '30 days', effectivenessMeasure: 'No key fraud control is both operated and independently certified by the same accountable function.', escalationThreshold: 'Any assurance reviewer assigned operational ownership of the control under review.', relatedScenarioTypes: ['governance_accountability_failure']
  },
  'D3-Q03': {
    questionCode: 'D3-Q03', domainCode: 'D3', controlObjective: 'Prevent fictitious, conflicted or misrepresented suppliers from entering the approved vendor population.', expectedStandard: 'Every supplier is verified against legal identity, ownership, tax/banking and risk indicators before activation, with enhanced review for high-risk suppliers.', fraudMechanism: 'A fictitious or conflicted supplier can be approved and used to route manipulated purchases or payments.', currentStateDiagnosis: diagnosis('Supplier-onboarding verification'),
    recommendedControlDesign: 'Procurement performs a pre-activation checklist across every proposed supplier, independently verifies registration and bank ownership, screens beneficial owners and conflicts, risk-rates the supplier, and blocks ERP activation until a second reviewer signs; the vendor master retains the evidence package.', executiveAccountability: 'CFO / COO', processOwnership: 'Procurement / Vendor Master', oversightFunction: 'Risk / Compliance', supportingFunctions: ['Finance', 'Legal', 'Accounts Payable'], operatingFrequency: 'Before every supplier activation; annual refresh for high-risk suppliers', evidenceRequired: ['Completed onboarding checklist', 'Independent registration and bank verification', 'Beneficial-ownership/conflict screening', 'Second-reviewer approval'], minimumAcceptableEvidenceCharacteristics: ['Covers the full supplier population added in the period', 'Evidence predates activation', 'Reviewer is different from requester'], dependencies: ['Controlled vendor-master workflow'], implementationDifficulty: 'Moderate', targetPeriod: '60 days', effectivenessMeasure: '100% of newly activated suppliers have a complete, pre-activation evidence pack and independent approval.', escalationThreshold: 'Any supplier activated before verification or any ownership/conflict match unresolved.', relatedScenarioTypes: ['supplier_onboarding_fraud']
  },
  'D3-Q04': {
    questionCode: 'D3-Q04', domainCode: 'D3', controlObjective: 'Keep ordinary system and data access aligned to current job responsibilities.', expectedStandard: 'All in-scope user access maps to an approved role, is reviewed by the business owner each quarter and is removed promptly after role change or exit.', fraudMechanism: 'Stale or excessive access lets staff initiate, approve or conceal activity outside their current responsibilities.', currentStateDiagnosis: diagnosis('Role-based user-access governance'), recommendedControlDesign: 'System owners export the complete active-user population quarterly; line managers compare every entitlement to the approved role matrix, record keep/remove decisions, and route exceptions to IT for closure within 10 business days; Risk samples completed reviews and overdue removals are escalated to the COO.', executiveAccountability: 'COO', processOwnership: 'Business system owners', oversightFunction: 'Risk / Internal Audit', supportingFunctions: ['IT', 'HR', 'Line Management'], operatingFrequency: 'Quarterly and on every joiner, mover or leaver event', evidenceRequired: ['Complete user-entitlement export', 'Approved role-to-access matrix', 'Manager recertification decisions', 'Exception and removal tickets'], minimumAcceptableEvidenceCharacteristics: ['Reconciles to the complete active-user population', 'Shows reviewer, decision and date per entitlement', 'Includes closure evidence for removals'], dependencies: ['Reliable HR joiner/mover/leaver feed', 'Named system owners'], implementationDifficulty: 'Moderate', targetPeriod: '60 days', effectivenessMeasure: '100% population reviewed quarterly and 95% of removal exceptions closed within 10 business days.', escalationThreshold: 'Any missed quarterly review, unassigned account or removal overdue beyond 10 business days.', relatedScenarioTypes: ['access_abuse', 'segregation_of_duties_bypass']
  },
  'D4-Q02': {
    questionCode: 'D4-Q02', domainCode: 'D4', controlObjective: 'Ensure generated fraud and control exceptions are actually investigated and resolved.', expectedStandard: 'The complete alert population is assigned, triaged to risk-based SLAs, dispositioned with evidence and independently reviewed for ageing and quality.', fraudMechanism: 'Unreviewed exceptions allow suspicious transactions or control overrides to continue without challenge.', currentStateDiagnosis: diagnosis('Exception-report review'), recommendedControlDesign: 'The monitoring owner generates a complete daily or weekly exception queue, assigns each alert to a trained reviewer, records investigation evidence and disposition, and escalates high-risk alerts immediately and all overdue alerts weekly; Risk performs a monthly closure-quality sample.', executiveAccountability: 'CFO / COO', processOwnership: 'Fraud monitoring owner', oversightFunction: 'Head of Risk', supportingFunctions: ['Finance', 'Operations', 'IT'], operatingFrequency: 'Daily/weekly triage; weekly ageing escalation; monthly quality review', evidenceRequired: ['Exception population and control totals', 'Alert investigation log', 'Disposition evidence', 'Monthly quality-review sample'], minimumAcceptableEvidenceCharacteristics: ['Shows completeness reconciliation', 'Records reviewer, timestamps and rationale', 'Separates closure-quality reviewer from alert investigator'], dependencies: ['Defined risk-based alert SLAs'], implementationDifficulty: 'Moderate', targetPeriod: '60 days', effectivenessMeasure: '95% of alerts closed within SLA and fewer than 5% unsupported closures in monthly samples.', escalationThreshold: 'Any high-risk alert unassigned after one business day or SLA breach rate above 5%.', relatedScenarioTypes: ['transaction_anomaly']
  },
  'D5-Q01': {
    questionCode: 'D5-Q01', domainCode: 'D5', controlObjective: 'Create a repeatable, coordinated response to suspected fraud.', expectedStandard: 'A documented plan defines intake, severity, command roles, containment, legal/evidence decisions, communications and closure, and is rehearsed annually.', fraudMechanism: 'Improvised response delays containment, creates conflicting decisions and allows loss or concealment to continue.', currentStateDiagnosis: diagnosis('Fraud incident-response governance'), recommendedControlDesign: 'The incident-response lead maintains a version-controlled plan covering every reported fraud incident, names an incident commander and deputies, classifies severity at intake, convenes Legal/HR/IT/Finance roles, records decisions and containment actions, and runs an annual tabletop with tracked remediation.', executiveAccountability: 'COO / General Counsel', processOwnership: 'Fraud incident-response lead', oversightFunction: 'Legal / Compliance', supportingFunctions: ['HR', 'IT Security', 'Finance', 'Communications'], operatingFrequency: 'On every suspected incident; annual tabletop and post-incident review', evidenceRequired: ['Approved incident-response plan', 'Incident decision and action log', 'Annual tabletop record', 'Lessons-learned tracker'], minimumAcceptableEvidenceCharacteristics: ['Names commander, deputies and severity triggers', 'Timestamps decisions and assigned actions', 'Shows tabletop findings closed'], dependencies: ['Reporting intake channel', 'Evidence-preservation procedure'], implementationDifficulty: 'Moderate', targetPeriod: '30 days', effectivenessMeasure: 'All incidents receive a severity decision within four hours and annual tabletop actions close by due date.', escalationThreshold: 'Severe incident not escalated within four hours or annual tabletop overdue.', relatedScenarioTypes: ['incident_response_breakdown']
  },
  'D5-Q05': {
    questionCode: 'D5-Q05', domainCode: 'D5', controlObjective: 'Identify, preserve and account for fraud evidence so integrity and provenance can be demonstrated.', expectedStandard: 'Evidence is collected under legal direction where needed, hashed or sealed, logged through every transfer, access-restricted and retained under an approved schedule.', fraudMechanism: 'Uncontrolled collection or transfer can alter, lose or contaminate evidence, undermining investigation, recovery or disciplinary action.', currentStateDiagnosis: diagnosis('Fraud evidence preservation and chain of custody'), recommendedControlDesign: 'The investigation lead opens an evidence register for every material case; trained custodians identify sources, create forensic copies or sealed originals, record hashes/seal numbers, collector/time/location and every transfer, store evidence in access-controlled repositories, and escalate any custody break immediately to Legal.', executiveAccountability: 'General Counsel / COO', processOwnership: 'Investigation lead / Evidence custodian', oversightFunction: 'Legal / Compliance', supportingFunctions: ['IT Security', 'HR', 'Records Management'], operatingFrequency: 'At collection and every transfer; quarterly custody-log review', evidenceRequired: ['Evidence register', 'Chain-of-custody forms', 'Hash or seal records', 'Repository access log', 'Retention/legal-hold instruction'], minimumAcceptableEvidenceCharacteristics: ['Unique evidence identifier on every item', 'Unbroken timestamped custody trail', 'Hash or seal reconciles at handover'], dependencies: ['Incident-response severity process', 'Approved secure evidence repository'], implementationDifficulty: 'High', targetPeriod: '60 days', effectivenessMeasure: '100% of sampled material-case evidence has a complete custody trail and matching integrity check.', escalationThreshold: 'Any unexplained custody gap, integrity mismatch or unauthorised repository access.', relatedScenarioTypes: ['evidence_compromise']
  },
  'D6-Q01': {
    questionCode: 'D6-Q01', domainCode: 'D6', controlObjective: 'Provide a safe, confidential route for internal and relevant external fraud concerns.', expectedStandard: 'A confidential and, where lawful, anonymous channel is continuously available, independently administered, access-restricted and protected by anti-retaliation escalation.', fraudMechanism: 'If reporters fear exposure or retaliation, early warning is suppressed and fraud can continue undetected.', currentStateDiagnosis: diagnosis('Confidential or anonymous reporting'), recommendedControlDesign: 'The ethics owner operates a web/telephone channel available to the full defined population, assigns case IDs without exposing reporter identity, limits case access by role, routes allegations away from implicated managers, acknowledges reports within two business days and reports retaliation concerns directly to the audit-committee chair.', executiveAccountability: 'Chair of Audit Committee / CEO', processOwnership: 'Ethics / Compliance lead', oversightFunction: 'Audit Committee', supportingFunctions: ['HR', 'Legal', 'IT Security'], operatingFrequency: 'Continuous intake; monthly case-ageing review; annual channel test', evidenceRequired: ['Channel configuration and availability test', 'Role-based case access list', 'Anonymised case register', 'Anti-retaliation escalation records'], minimumAcceptableEvidenceCharacteristics: ['Supports confidential and anonymous intake', 'Shows restricted identities and conflict routing', 'Tracks acknowledgement and ageing'], dependencies: ['Independent case triage process', 'Anti-retaliation policy'], implementationDifficulty: 'Moderate', targetPeriod: '60 days', effectivenessMeasure: '100% of reports acknowledged within two business days and annual anonymous-channel test completed successfully.', escalationThreshold: 'Channel outage over one business day, reporter identity disclosed without authority or any retaliation allegation.', relatedScenarioTypes: ['suppressed_reporting']
  },
  'D7-Q01': {
    questionCode: 'D7-Q01', domainCode: 'D7', controlObjective: 'Risk-screen every supplier, contractor or third party before engagement.', expectedStandard: 'All third parties receive proportionate identity, ownership, sanctions/conflict and capability checks before contracting, with enhanced approval for high-risk relationships.', fraudMechanism: 'Unverified third parties can conceal related parties, fictitious businesses or integrity concerns before receiving access or funds.', currentStateDiagnosis: diagnosis('Third-party pre-engagement due diligence'), recommendedControlDesign: 'The vendor-risk owner risk-rates every proposed third party, verifies legal identity and beneficial ownership from independent sources, screens sanctions/adverse and employee conflicts, documents capability and bank ownership, and requires Compliance approval for high-risk cases before contract signature or system activation.', executiveAccountability: 'CFO / COO', processOwnership: 'Procurement / Vendor Risk', oversightFunction: 'Compliance / Risk', supportingFunctions: ['Legal', 'Finance', 'Business Sponsor'], operatingFrequency: 'Before engagement; annual refresh for high-risk third parties', evidenceRequired: ['Third-party risk rating', 'Identity and beneficial-ownership verification', 'Sanctions/adverse/conflict screening', 'High-risk approval'], minimumAcceptableEvidenceCharacteristics: ['Evidence predates engagement', 'Uses independent source data', 'Documents match resolution and approver'], dependencies: ['Third-party inventory', 'Conflict-of-interest declarations'], implementationDifficulty: 'Moderate', targetPeriod: '60 days', effectivenessMeasure: '100% of new third parties have completed risk-tiered due diligence before engagement.', escalationThreshold: 'Any engagement before due diligence or unresolved ownership, sanctions or conflict match.', relatedScenarioTypes: ['supplier_onboarding_fraud']
  },
  'D7-Q04': {
    questionCode: 'D7-Q04', domainCode: 'D7', controlObjective: 'Prevent invoice manipulation and fraudulent vendor bank-detail changes before payment release.', expectedStandard: 'Every bank-detail change is verified independently through a trusted pre-existing contact and segregated from payment approval; invoices are matched to approved supplier and purchasing records.', fraudMechanism: 'An impersonator or insider can redirect legitimate payments by submitting altered invoices or false bank details.', currentStateDiagnosis: diagnosis('Supplier payment and bank-detail-change verification'), recommendedControlDesign: 'Accounts Payable quarantines every bank-detail change, retrieves a contact from the pre-change vendor master, completes and records an outbound callback, obtains second-person approval from someone outside vendor-master maintenance, blocks payment until verification, and gives the CFO a monthly report of all changes, failures and bypass attempts.', executiveAccountability: 'CFO', processOwnership: 'Accounts Payable / Vendor Master', oversightFunction: 'Finance Control / Internal Audit', supportingFunctions: ['Procurement', 'Treasury', 'IT'], operatingFrequency: 'Every change and invoice; monthly exception reporting', evidenceRequired: ['Bank-detail-change request', 'Pre-existing contact record and callback log', 'Independent approval', 'Payment hold/release audit trail', 'Monthly CFO exception report'], minimumAcceptableEvidenceCharacteristics: ['Callback number predates the request', 'Requester, verifier and approver are separated', 'Covers the complete bank-change population'], dependencies: ['Controlled vendor master', 'Supplier due diligence'], implementationDifficulty: 'Moderate', targetPeriod: '30 days', effectivenessMeasure: '100% of bank-detail changes independently verified before the first payment; zero unapproved bypasses.', escalationThreshold: 'Any unverified change released, callback mismatch or attempt to bypass segregation.', relatedScenarioTypes: ['supplier_payment_redirection']
  },
  'D8-Q02': {
    questionCode: 'D8-Q02', domainCode: 'D8', controlObjective: 'Detect suspicious login, account, access and transaction behaviour on digital platforms.', expectedStandard: 'Risk-based monitoring covers material digital events, alerts are triaged to defined SLAs and rules are tuned from confirmed outcomes.', fraudMechanism: 'Account compromise or misuse can persist when anomalous login, access or transaction patterns are not surfaced and investigated.', currentStateDiagnosis: diagnosis('Suspicious digital-activity monitoring'), recommendedControlDesign: 'The security monitoring owner inventories material login, privilege, profile and transaction events, implements risk rules across the full in-scope event feed, assigns alerts to trained analysts, preserves dispositions and escalates high-risk account compromise immediately; monthly tuning uses confirmed true/false positives.', executiveAccountability: 'Chief Technology Officer', processOwnership: 'Security monitoring / SOC', oversightFunction: 'Information Security / Risk', supportingFunctions: ['Fraud Operations', 'Digital Product', 'Data Engineering'], operatingFrequency: 'Continuous monitoring; monthly rule tuning', evidenceRequired: ['In-scope event inventory', 'Monitoring-rule catalogue', 'Alert case records', 'Monthly tuning and coverage report'], minimumAcceptableEvidenceCharacteristics: ['Reconciles monitored events to source feeds', 'Maps each rule to a risk and SLA', 'Records evidence-based disposition'], dependencies: ['Reliable digital telemetry', 'Incident-response routing'], implementationDifficulty: 'High', targetPeriod: '90 days', effectivenessMeasure: 'All priority event feeds monitored and 95% of high-risk alerts triaged within SLA.', escalationThreshold: 'Priority feed outage, high-risk alert outside SLA or confirmed compromise not escalated.', relatedScenarioTypes: ['account_takeover', 'digital_access_abuse']
  },
  'D8-Q04': {
    questionCode: 'D8-Q04', domainCode: 'D8', controlObjective: 'Restrict and independently recertify privileged, administrator and sensitive-data access.', expectedStandard: 'Every privileged account is named, justified, least-privileged, strongly authenticated, logged and independently recertified quarterly; emergency access expires automatically.', fraudMechanism: 'Excess or unmanaged administrator rights allow records, controls and logs to be altered or concealed.', currentStateDiagnosis: diagnosis('Privileged and administrator access governance'), recommendedControlDesign: 'IT Security maintains a complete privileged-account register, links each human and service account to an owner and approved justification, enforces separate named admin identities and MFA, records privileged sessions, and sends the full population quarterly to system owners and Risk for independent keep/remove certification; removals close within 24 hours for leavers and five business days otherwise.', executiveAccountability: 'Chief Technology Officer', processOwnership: 'Identity and Access Management', oversightFunction: 'Information Security / Internal Audit', supportingFunctions: ['System Owners', 'HR', 'Risk'], operatingFrequency: 'Continuous logging; quarterly recertification; event-driven removal', evidenceRequired: ['Privileged-account register', 'Approval and business justification', 'Quarterly independent recertification', 'Privileged-session/access logs', 'Removal tickets'], minimumAcceptableEvidenceCharacteristics: ['Covers human, service, shared and emergency accounts', 'Separates reviewer from account administrator', 'Shows owner, decision, date and closure'], dependencies: ['Authoritative identity inventory', 'HR leaver feed', 'Central logging'], implementationDifficulty: 'High', targetPeriod: '60 days', effectivenessMeasure: '100% privileged accounts recertified quarterly; leaver access removed within 24 hours; zero unjustified shared admin accounts.', escalationThreshold: 'Any unknown or unjustified privileged account, missed recertification or leaver access beyond 24 hours.', relatedScenarioTypes: ['privileged_access_exploitation']
  },
  'D8-Q05': {
    questionCode: 'D8-Q05', domainCode: 'D8', controlObjective: 'Detect misuse, unauthorised transactions, suspicious data changes and digital-channel abuse.', expectedStandard: 'Monitoring joins user, transaction and change events across material digital channels, with risk-based triage and retained investigation evidence.', fraudMechanism: 'Malicious or compromised users can manipulate data or transact without detection when digital events are reviewed in isolation.', currentStateDiagnosis: diagnosis('Digital misuse detection'), recommendedControlDesign: 'Digital Operations and Security define misuse cases for unauthorised transactions, sensitive-data changes and channel abuse, monitor the complete in-scope event population, link events by user/device/account, triage alerts to SLA and review monthly control totals and missed-case feedback.', executiveAccountability: 'Chief Technology Officer / COO', processOwnership: 'Digital fraud operations', oversightFunction: 'Information Security / Risk', supportingFunctions: ['Data Engineering', 'Finance', 'Customer Operations'], operatingFrequency: 'Continuous; monthly coverage and effectiveness review', evidenceRequired: ['Misuse-case catalogue', 'Event-feed reconciliation', 'Alert investigations', 'Monthly effectiveness report'], minimumAcceptableEvidenceCharacteristics: ['Maps scenarios to events and thresholds', 'Proves source-feed completeness', 'Records analyst rationale and escalation'], dependencies: ['Integrated digital event data', 'Alert case-management process'], implementationDifficulty: 'High', targetPeriod: '90 days', effectivenessMeasure: 'All priority misuse cases monitored, with 95% high-risk alerts triaged within SLA and monthly missed-case review completed.', escalationThreshold: 'Missing priority feed, confirmed unauthorised transaction not alerted or high-risk SLA breach.', relatedScenarioTypes: ['digital_transaction_abuse']
  },
  'D9-Q01': {
    questionCode: 'D9-Q01', domainCode: 'D9', controlObjective: 'Equip staff to recognise and act on fraud risks specific to their roles.', expectedStandard: 'Role-based fraud learning is completed at induction and annually, refreshed for emerging risks and tested for understanding and behaviour.', fraudMechanism: 'Generic or stale awareness leaves staff vulnerable to role-specific manipulation, social engineering and control bypass requests.', currentStateDiagnosis: diagnosis('Role-relevant fraud awareness'), recommendedControlDesign: 'The People lead maps roles to current fraud scenarios, assigns short mandatory modules at induction and annually, tests decision-making with scenario questions, tracks the complete employee population, escalates overdue completion to line executives and refreshes content after material incidents or threat changes.', executiveAccountability: 'Chief People Officer / COO', processOwnership: 'Learning and Development', oversightFunction: 'Risk / Compliance', supportingFunctions: ['Fraud Risk', 'IT Security', 'Line Management'], operatingFrequency: 'At induction; annual refresher; event-driven content refresh', evidenceRequired: ['Role-to-training matrix', 'Current scenario-based content', 'Employee completion and assessment results', 'Overdue escalation log'], minimumAcceptableEvidenceCharacteristics: ['Reconciles to the active employee population', 'Uses role-specific scenarios', 'Records pass threshold, retries and escalation'], dependencies: ['Accurate HR population and role data', 'Current fraud threat input'], implementationDifficulty: 'Low', targetPeriod: '90 days', effectivenessMeasure: 'At least 95% on-time completion and 80% minimum knowledge score, with all overdue cases escalated.', escalationThreshold: 'Completion below 95%, material role omitted or repeated assessment failure.', relatedScenarioTypes: ['social_engineering']
  }
};

export function getQuestionPlaybook(questionCode: string): QuestionControlPlaybook | null {
  return PLAYBOOKS[questionCode] ?? null;
}

export function hasQuestionPlaybook(questionCode: string): boolean {
  return questionCode in PLAYBOOKS;
}

export function listQuestionPlaybooks(): QuestionControlPlaybook[] {
  return Object.values(PLAYBOOKS).sort((a, b) => a.questionCode.localeCompare(b.questionCode));
}
