import type { MaterialFinding } from './types';

export interface RiskPathway {
  key: string;
  title: string;
  cause: string;
  riskEvent: string;
  financialImpact: string;
  operationalImpact: string;
  legalRegulatoryImpact?: string;
  reputationalImpact?: string;
  consequence: 'Low' | 'Moderate' | 'High' | 'Severe';
}

const PATHWAY_BY_QUESTION: Record<string, RiskPathway> = {
  'D1-Q01': { key: 'GOVERNANCE-ACCOUNTABILITY', title: 'Fraud-risk accountability and escalation failure', cause: 'executive fraud-risk accountability, authority and escalation are not supported by the required operating evidence', riskEvent: 'material fraud-control gaps remain unresolved or accepted without an authorised decision', financialImpact: 'losses continue because required resources or corrective action are delayed', operationalImpact: 'cross-functional actions remain ownerless or overdue', reputationalImpact: 'leadership may be unable to demonstrate active stewardship of known fraud risks', consequence: 'High' },
  'D1-Q04': { key: 'GOVERNANCE-ACCOUNTABILITY', title: 'Fraud-risk accountability and escalation failure', cause: 'management ownership and independent assurance responsibilities are not clearly separated', riskEvent: 'a material control is operated and certified without independent challenge', financialImpact: 'control failure remains undetected and permits avoidable loss', operationalImpact: 'assurance conclusions cannot be relied upon for remediation decisions', reputationalImpact: 'governance reporting may provide false comfort', consequence: 'High' },
  'D3-Q03': { key: 'SUPPLIER-ONBOARDING', title: 'Fictitious or conflicted supplier enters the vendor population', cause: 'supplier identity, ownership, banking and conflict checks are incomplete or not evidenced before activation', riskEvent: 'a fictitious, conflicted or misrepresented supplier is approved and used for purchasing or payment', financialImpact: 'funds are paid to an illegitimate or related party', operationalImpact: 'procurement and vendor-master integrity are compromised', legalRegulatoryImpact: 'sanctions, conflict or procurement obligations may be breached', reputationalImpact: 'stakeholders lose confidence in supplier governance', consequence: 'Severe' },
  'D7-Q01': { key: 'SUPPLIER-ONBOARDING', title: 'Fictitious or conflicted supplier enters the vendor population', cause: 'risk-tiered third-party due diligence is incomplete or not evidenced before engagement', riskEvent: 'an unsuitable, conflicted or misrepresented third party gains access, authority or funds', financialImpact: 'payments or assets are exposed to an illegitimate third party', operationalImpact: 'the organisation becomes dependent on an unverified provider', legalRegulatoryImpact: 'contracting, sanctions or integrity obligations may be breached', reputationalImpact: 'third-party misconduct is attributed to the organisation', consequence: 'Severe' },
  'D7-Q04': { key: 'SUPPLIER-PAYMENT-REDIRECTION', title: 'Supplier payment is redirected through impersonation', cause: 'invoice and bank-detail changes are not independently verified through a trusted pre-existing contact', riskEvent: 'an impersonator or insider redirects a legitimate supplier payment to an unauthorised account', financialImpact: 'a payment is irrecoverably transferred to a fraud-controlled account', operationalImpact: 'supplier settlement and service continuity are disrupted', legalRegulatoryImpact: 'recovery, disclosure or dispute obligations may arise', reputationalImpact: 'suppliers lose confidence in payment controls', consequence: 'Severe' },
  'D3-Q04': { key: 'UNAUTHORISED-ACCESS', title: 'Unauthorised system access enables transaction or record manipulation', cause: 'role-based access is not completely reviewed and removed when responsibilities change', riskEvent: 'a user or compromised credential uses excess access to initiate, approve or conceal unauthorised activity', financialImpact: 'transactions or assets are manipulated for direct loss', operationalImpact: 'system records and segregation of duties cannot be relied upon', legalRegulatoryImpact: 'data or access-control obligations may be breached', reputationalImpact: 'stakeholders lose trust in system integrity', consequence: 'Severe' },
  'D8-Q04': { key: 'UNAUTHORISED-ACCESS', title: 'Unauthorised system access enables transaction or record manipulation', cause: 'privileged, administrator or sensitive-data access is not completely restricted, logged and independently recertified', riskEvent: 'a privileged user or compromised administrator identity alters records, controls or logs without timely detection', financialImpact: 'high-impact transactions or data can be manipulated', operationalImpact: 'critical systems and audit trails lose integrity', legalRegulatoryImpact: 'security and personal-data obligations may be breached', reputationalImpact: 'confidence in digital controls is damaged', consequence: 'Severe' },
  'D4-Q02': { key: 'DETECTION-REVIEW', title: 'Suspicious activity remains unresolved in the exception queue', cause: 'the complete population of alerts and exception reports is not evidenced as assigned, investigated and independently reviewed', riskEvent: 'material anomalous activity is missed, closed without support or allowed to remain overdue', financialImpact: 'losses compound while suspicious activity continues', operationalImpact: 'monitoring backlogs and unsupported closures weaken detection', consequence: 'High' },
  'D5-Q01': { key: 'INCIDENT-RESPONSE', title: 'Fraud incident response is delayed or uncoordinated', cause: 'incident command, severity, containment and decision roles are not documented and rehearsed', riskEvent: 'a suspected fraud is handled inconsistently, delaying containment and escalation', financialImpact: 'losses and recovery costs increase while action is delayed', operationalImpact: 'containment, legal, HR, IT and communications decisions conflict or stall', legalRegulatoryImpact: 'notification or investigation duties may be missed', reputationalImpact: 'poor crisis handling amplifies stakeholder harm', consequence: 'Severe' },
  'D5-Q05': { key: 'EVIDENCE-INTEGRITY', title: 'Fraud evidence loses integrity or chain of custody', cause: 'evidence identification, preservation, integrity checks and custody transfers are not consistently controlled', riskEvent: 'material evidence is altered, lost, contaminated or cannot be shown to be authentic', financialImpact: 'recovery, disciplinary or legal outcomes are weakened', operationalImpact: 'investigations must be repeated or abandoned', legalRegulatoryImpact: 'evidence, retention or legal-hold duties may be breached', reputationalImpact: 'the organisation cannot substantiate its response', consequence: 'High' },
  'D6-Q01': { key: 'REPORTING-SUPPRESSION', title: 'Fraud concerns remain unreported or are routed to conflicted management', cause: 'confidential or anonymous reporting is not trusted, independently routed and protected from retaliation', riskEvent: 'a person who observes suspected fraud does not report it or the concern is suppressed', financialImpact: 'fraud continues longer before detection', operationalImpact: 'early-warning information never reaches an independent reviewer', legalRegulatoryImpact: 'whistleblower-protection duties may be compromised', reputationalImpact: 'staff trust and reporting culture deteriorate', consequence: 'High' },
  'D8-Q02': { key: 'DIGITAL-MISUSE', title: 'Digital account compromise or misuse is not detected promptly', cause: 'material login, access, profile and transaction events are not completely monitored and triaged', riskEvent: 'a compromised or malicious identity uses digital channels without timely detection and response', financialImpact: 'unauthorised transactions or account changes cause direct loss', operationalImpact: 'digital operations must contain and investigate a wider incident', legalRegulatoryImpact: 'security or personal-data notification duties may arise', reputationalImpact: 'customers and partners lose trust in digital channels', consequence: 'Severe' },
  'D8-Q05': { key: 'DIGITAL-MISUSE', title: 'Digital account compromise or misuse is not detected promptly', cause: 'digital events are not joined and monitored for misuse, unauthorised transactions and suspicious data changes', riskEvent: 'malicious or compromised users manipulate digital activity without a complete alert trail', financialImpact: 'unauthorised transactions create direct loss', operationalImpact: 'digital records and customer operations require investigation and correction', legalRegulatoryImpact: 'security or personal-data obligations may be triggered', reputationalImpact: 'confidence in digital services is damaged', consequence: 'Severe' },
  'D9-Q01': { key: 'ROLE-AWARENESS', title: 'Staff fail to recognise role-specific fraud manipulation', cause: 'fraud guidance is not current, role-specific and tested for understanding', riskEvent: 'an employee complies with a fraudulent request or misses a warning sign relevant to their role', financialImpact: 'social engineering or control bypass causes avoidable loss', operationalImpact: 'staff become the entry point for process compromise', consequence: 'Moderate' }
};

export function riskPathwayForFinding(finding: MaterialFinding): RiskPathway {
  return PATHWAY_BY_QUESTION[finding.questionCode] ?? {
    key: `CONTROL-${finding.questionCode}`,
    title: `${finding.domainName} control effectiveness risk`,
    cause: finding.materialityClass === 'assurance_priority'
      ? 'the self-reported control position has not yet been independently validated with operating evidence'
      : 'the assessed control design or operation does not meet the exact expected standard',
    riskEvent: finding.fraudMechanism.replace(/[.]$/, '').replace(/^./, (value) => value.toLowerCase()),
    financialImpact: finding.likelyFinancialImpact,
    operationalImpact: finding.likelyOperationalImpact,
    consequence: finding.isHardGate ? 'Severe' : finding.isCriticalControl ? 'High' : 'Moderate'
  };
}
