import type { ExposureAnswerRecord, GapQuestionRecord, MaturityCapEventRecord, ScoreRunRecord } from '../types';

export type ImplementationDifficulty = 'Low' | 'Moderate' | 'High';
export type TargetPeriod = '30 days' | '60 days' | '90 days';

/**
 * A single material control finding, evidence-linked to one real assessment question/response.
 * Every field is either sourced directly from AssembledReportData or from a per-domain playbook
 * (domain-playbooks.ts) -- nothing here is free-text generated by a model. See material-findings.ts.
 */
export interface MaterialFinding {
  id: string;
  title: string;
  domainCode: string;
  domainName: string;
  questionCode: string;
  questionPrompt: string;
  responseValue: number | null;
  responseMeaning: string;
  isCriticalControl: boolean;
  isHardGate: boolean;
  gapClassification: 'critical' | 'major';
  maturityCapStatus: 'capping' | 'not_capping';
  relatedCapRuleCode: string | null;
  linkedExposureFactorCodes: string[];
  diagnosis: string;
  whyItMatters: string;
  fraudMechanism: string;
  likelyFinancialImpact: string;
  likelyOperationalImpact: string;
  expectedControlStandard: string;
  evidenceToRequest: string[];
  recommendedControl: string;
  accountableOwner: string;
  oversightFunction: string;
  operatingFrequency: string;
  implementationDifficulty: ImplementationDifficulty;
  targetPeriod: TargetPeriod;
  effectivenessMeasure: string;
  selfAssessmentLimitation: string;
}

export type ContradictionPattern =
  | 'strong_detection_weak_response'
  | 'strong_identification_weak_improvement'
  | 'strong_domain_failed_critical_control'
  | 'exposure_outpaces_control'
  | 'whistleblowing_present_but_weak'
  | 'access_control_gap_operational_and_digital';

export interface Contradiction {
  id: string;
  pattern: ContradictionPattern;
  title: string;
  drivingResponses: string;
  whyItMatters: string;
  falseComfortRisk: string;
  whatLeadershipShouldVerify: string;
  fraudPathwayEnabled: string;
  linkedFindingIds: string[];
  linkedRiskId: string | null;
}

export interface PlausibleScenario {
  id: string;
  title: string;
  confirmedOperatingContext: string[];
  entryPoint: string;
  linkedControlWeaknesses: string[];
  fraudSequence: string;
  concealmentMechanism: string;
  whyControlsMayNotCatchIt: string;
  earlyWarningIndicators: string[];
  likelyImpact: string[];
  immediateContainment: string;
  longerTermResponse: string;
  linkedFindingIds: string[];
  linkedRiskId: string;
  disclaimer: string;
}

export type Likelihood = 'Low' | 'Moderate' | 'High';
export type Impact = 'Low' | 'Moderate' | 'High' | 'Severe';

export interface RiskRegisterEntry {
  id: string;
  title: string;
  riskStatement: string;
  linkedFindingIds: string[];
  affectedDomain: string;
  likelihood: Likelihood;
  impact: Impact;
  priority: 'Low' | 'Medium' | 'High' | 'Critical';
  currentControlPosition: string;
  requiredTreatment: string;
  accountableOwner: string;
  targetDate: string;
  effectivenessMeasure: string;
  assessmentConfidence: 'Self-assessment only, not independently verified';
  remainingLimitation: string;
}

export interface ControlImprovementEntry {
  id: string;
  linkedFindingId: string;
  linkedRiskId: string;
  currentState: string;
  targetState: string;
  controlObjective: string;
  controlDesign: string;
  accountableOwner: string;
  oversightOwner: string;
  supportingFunctions: string[];
  operatingFrequency: string;
  requiredEvidence: string[];
  implementationDependency: string;
  implementationDifficulty: ImplementationDifficulty;
  targetPeriod: TargetPeriod;
  effectivenessTest: string;
  escalationThreshold: string;
}

export interface EvidenceChecklistItem {
  id: string;
  artefact: string;
  linkedFindingId: string;
  linkedRiskId: string;
  likelyOwner: string;
  provesWhat: string;
  expectedRecency: string;
  minimumAcceptableCharacteristics: string;
  reviewStatus: 'Not yet requested';
}

export interface LeadershipDecision {
  id: string;
  decisionRequired: string;
  evidenceDrivingIt: string;
  whyNow: string;
  recommendedDecision: string;
  accountableExecutive: string;
  deadline: string;
  consequenceOfDelay: string;
  immediateNextDeliverable: string;
}

export interface RoadmapAction {
  id: string;
  period: TargetPeriod;
  deliverable: string;
  accountableOwner: string;
  linkedFindingId: string;
  linkedRiskId: string;
  dependency: string;
  implementationDifficulty: ImplementationDifficulty;
  successMeasure: string;
  evidenceOfCompletion: string;
}

export interface FunctionalAgendaItem {
  function: string;
  question: string;
  linkedFindingId: string | null;
  linkedRiskId: string | null;
}

export interface AdvisoryEvidenceModel {
  materialFindings: MaterialFinding[];
  contradictions: Contradiction[];
  scenarios: PlausibleScenario[];
  riskRegister: RiskRegisterEntry[];
  controlImprovements: ControlImprovementEntry[];
  evidenceChecklist: EvidenceChecklistItem[];
  leadershipDecisions: LeadershipDecision[];
  roadmapActions: RoadmapAction[];
  functionalAgenda: FunctionalAgendaItem[];
}

/** Inputs the evidence-model builder actually consumes, re-exported here for convenience. */
export interface EvidenceModelInput {
  organisationName: string;
  scoreRun: ScoreRunRecord;
  domainResults: { domainCode: string; domainName: string; rawScore: number | null; weightPct: number }[];
  criticalMajorGaps: GapQuestionRecord[];
  maturityCapEvents: MaturityCapEventRecord[];
  exposureAnswers: ExposureAnswerRecord[];
}
