/**
 * Presentation-only customer explanations for the published adaptive graph.
 *
 * This map deliberately lives outside the graph JSON: changing a definition here must not alter
 * routing, scoring, weights, gates or the approved graph fingerprint. Every entry is keyed by the
 * stable customer-visible node id and is short enough to be useful beside the question.
 */
export const CUSTOMER_HELP_TEXT: Readonly<Record<string, string>> = Object.freeze({
  G01: 'Choose the broadest description of how the organisation mainly operates today. If several activities apply, use the mixed option rather than focusing on a single department.',
  G02: 'Include regular employees and the normal workforce footprint. A practical headcount range is enough; do not count occasional visitors or customers.',
  G03: 'Think about any work, goods or information another organisation handles for you, including a group team. Include arrangements where your organisation still owns the risk even if it does not perform the activity itself.',
  G04: 'Think about the person or team that approves suppliers and remains accountable for the relationship after onboarding. This may be local, a group/shared-service team or a delegated provider.',
  G05: 'Consider who sets sourcing requirements, runs procurement decisions and manages purchasing controls. The answer is about the operating owner, not only who raises a purchase request.',
  G06: 'Include cash received, held, counted, transported or paid out during ordinary operations. Answer yes even if cash is only one part of the business model.',
  G07: 'Include items that can be lost, substituted or written off, such as goods held for sale, equipment, materials or company property.',
  G08: 'Consider who prepares payroll inputs, maintains the payroll master file and releases payroll for payment. This can be an internal team, shared service or provider.',
  G09: 'Think about the channels through which customers or users access services or transact, such as websites, apps, portals, platforms, messaging journeys or in-person channels.',
  G10: 'Include money received through websites, apps, terminals, portals or mobile journeys, whether the channel is yours or operated on your behalf.',
  G11: 'Include information that identifies a person or can be used to impersonate, verify or access an account. Examples include identity documents, contact details, employee records and authentication data.',
  G12: 'Consider whether authorised users can change financial, stock or similar records outside the normal automated process, including journals, overrides, write-offs or manual corrections.',
  G13: 'Include branches, stores, plants, offices, project sites or other locations where people, stock, cash or operations are managed.',
  G14: 'Include people engaged for a limited period or through an agency or subcontracting arrangement when their access or duties could affect a process.',
  G15: 'Consider remote access from home, client sites, mobile devices, third-party networks or support connections. Include access by employees and relevant external users.',
  G16: 'Focus on how challenge is applied in practice: for example one approver, two-person approval, a committee, or different rules by amount or risk.',
  G17: 'Include intermediaries who connect the organisation to customers, suppliers or public bodies, even if they do not sign contracts themselves.',

  'D1-Q01': 'A senior owner should have enough authority, visibility and access to resources to make fraud-risk decisions and see that actions are followed through.',
  'D1-Q02': 'Fraud risk is part of the organisation’s normal risk and governance conversations, rather than being treated only as an isolated compliance topic.',
  'D1-Q03': 'Look for a defined reporting rhythm and audience. Reporting should cover meaningful fraud risks, incidents and weaknesses, including what management needs to decide.',
  'D1-Q04': 'Look for named accountability that survives staff changes: who can accept an exposure, approve an action or require progress when a weakness remains?',
  'D1-Q05': 'The guidance should cover prevention, detection, reporting and handling. It should help a person know what to do when something appears suspicious, not only describe a policy principle.',
  'D1-Q06': 'Consider whether leaders receive relevant threat intelligence or trend updates early enough to adjust controls, awareness or priorities.',
  'D1-Q07': 'Independent review may be provided by internal audit, risk, a group function or another suitably independent party. The depth should fit the organisation’s scale and model.',
  'D10-Q01': 'A review should revisit both the fraud risks and the controls intended to address them. It should happen periodically and after material changes or incidents where appropriate.',
  'D10-Q02': 'Incident analysis looks beyond what happened to why it was possible, which controls failed or were bypassed, and what conditions allowed it to occur.',
  'D10-Q03': 'A useful lesson should result in a changed practice, system setting, training activity or review check, with someone responsible for confirming the change worked.',
  'D10-Q06': 'Leadership should periodically test whether important controls still have the people, tools, funding and operating fit needed for the current risk environment.',
  'D2-Q01': 'A structured assessment records the important fraud scenarios and control exposure, rather than relying only on informal knowledge or a past incident review.',
  'D2-Q02': 'A useful map links a possible loss event to the part of the business where it could happen, such as purchasing, payroll, revenue, refunds or cash handling.',
  'D2-Q03': 'Think about system implementations, new payment channels, process redesigns or product launches. The point is to consider fraud risk before the change goes live.',
  'D2-Q04': 'Refresh risk views when the operating model, customers, suppliers, technology or process changes materially, so that old assumptions do not remain unchallenged.',
  'D2-Q05': 'Consider risks arising from the organisation’s reliance on third parties, including ownership opacity, collusion, false vendors, bribery or weak downstream controls.',
  'D2-Q06': 'Emerging threats may come from sector events, geography, technology, organised fraud patterns or changes in how the organisation serves customers and suppliers.',
  'D2-Q07': 'Test realistic override routes: who could create and approve a record, change access, bypass a threshold or make an exception without challenge?',
  'D2-Q08': 'Walk through the customer journey from sign-up to service use and payment. Look for points where a fake identity, manipulated message or altered request could be accepted.',
  'D3-Q01': 'Segregation means one person cannot initiate, approve, process and reconcile a high-risk activity alone. Where staffing is limited, a documented compensating check may help.',
  'D3-Q02': 'Threshold approval should be defined by value, risk or activity type and should involve a reviewer with enough independence and authority to challenge the transaction.',
  'D3-Q03': 'Onboarding checks should establish that the supplier is real, who owns or controls it, and whether initial bank information is credible before approval.',
  'D3-Q04': 'Access should match the person’s current job needs and be removed or changed when duties change. This is about permission design, not merely having a user account.',
  'D3-Q05': 'Consider changes made outside the standard transaction flow, such as a credit, journal or write-off. A second person should check the reason, support and outcome when the change carries risk.',
  'D3-Q06': 'A periodic process review looks for unnecessary access, weak handoffs, unusual workarounds, single-person dependencies or other opportunities for manipulation.',
  'D3-Q07': 'High-risk roles may need rotation, secondary review, supervision or another compensating measure, particularly where duties cannot be fully separated.',
  'D3-Q08': 'Review access periodically against current roles and promptly remove access that is no longer needed, including access left after transfers or departures.',
  'D3-Q09': 'Check the final pre-payment review for unusual payees, duplicate amounts, last-minute account changes or records that should no longer be paid.',
  'D3-Q10': 'Cash safeguards include clear custody, independent counts, reconciliation to records and escalation of differences. Consider cash held at sites as well as central handling.',
  'D3-Q11': 'Physical asset safeguards include ownership records, access controls, counts or reconciliations and investigation of losses, substitutions or unexplained movements.',
  'D4-Q01': 'Monitoring should look for patterns that do not fit normal activity, including unusual timing, value, frequency, user behaviour or process exceptions.',
  'D4-Q02': 'An exception report is useful when alert thresholds, review ownership, response times and escalation steps are defined rather than left to personal judgement.',
  'D4-Q03': 'Look for a repeatable signal that flags activity outside an expected pattern and a person who reviews the result. A spreadsheet comparison, alert, reconciliation or dashboard can all serve this purpose.',
  'D4-Q04': 'Update detection when fraud methods, systems, products, channels or operational processes change, and after incidents reveal a blind spot.',
  'D4-Q05': 'Include misuse by employees, contractors, administrators and other insiders who may have legitimate access but use it outside an approved purpose.',
  'D4-Q06': 'The monitoring owner should know what signals require escalation and be empowered to pause, refer or investigate activity without waiting for informal permission.',
  'D4-Q07': 'A periodic effectiveness review checks whether alerts are relevant, reviewed on time, producing useful outcomes and still covering the current risk profile.',
  'D4-Q08': 'Include threats originating outside the organisation, such as deception by customers, vendors, intermediaries or cyber actors, and define which signals merit follow-up.',
  'D5-Q01': 'A response process should explain how a suspicion is received, triaged, protected, investigated, escalated, decided and closed, including who owns each step.',
  'D5-Q03': 'Decision rights should make clear who can triage, investigate, escalate, approve actions and close a case, including how conflicts or senior people are handled.',
  'D5-Q04': 'Good records preserve confidentiality and fair treatment while capturing the key facts, decisions, actions and reasons needed to understand how the case was handled.',
  'D5-Q05': 'Preservation includes identifying relevant documents, messages, system records or devices, controlling access and maintaining enough history to show what was handled.',
  'D5-Q06': 'External expertise may be appropriate for forensic work, legal privilege, cyber investigation, specialist interviewing or matters beyond internal capability.',
  'D6-Q01': 'A reporting channel should be reasonably confidential or anonymous, accessible to the relevant workforce and able to route a concern for independent handling.',
  'D6-Q02': 'People need practical awareness of warning signs and a clear understanding of how and when to use the reporting channel.',
  'D6-Q03': 'Independent handling means reports are reviewed by people who are not implicated and can escalate or protect the report when the usual chain is conflicted.',
  'D6-Q04': 'The organisation should make the non-retaliation expectation visible and explain how concerns about retaliation can themselves be raised and addressed.',
  'D6-Q05': 'Consider suppliers, customers, agents, contractors and other relevant outsiders who may see suspicious conduct but do not use the employee reporting route.',
  'D7-Q01': 'Due diligence should be proportionate to the relationship and may cover identity, ownership, reputation, conflicts, sanctions or other risk indicators before engagement.',
  'D7-Q02': 'Safeguards may include defined tender rules, independent evaluation, controlled communications, conflict declarations and records that make manipulation visible.',
  'D7-Q03': 'People involved in third-party decisions should disclose relevant personal or business interests and have those interests managed before decisions are made.',
  'D7-Q04': 'Payment checks should help detect false vendors, changed bank details, duplicate invoices and other manipulation, with independent verification for risky changes.',
  'D7-Q05': 'Higher-risk relationships should be revisited using current risk information, performance signals, incidents, ownership changes and control concerns.',
  'D7-Q06': 'Sample the owner’s review trail: what was checked, what exception was raised, who accepted it and whether the action was closed.',
  'D7-Q07': 'Consider how intermediary selection, commissions, sales activity, customer contact and outsourced services could create fraud or misconduct exposure.',
  'D8-Q01': 'Identity checks should be proportionate to the loss or harm that identity misuse could create and should apply at the relevant onboarding or access point.',
  'D8-Q02': 'Monitoring can combine internal logs, account activity, transaction signals and provider reports so that important behaviour is visible even when a third party operates one channel.',
  'D8-Q03': 'Test whether people can recognise an urgent impersonation attempt and know where to report it; include a short exercise or example relevant to their work.',
  'D8-Q04': 'Consider whether privileged access is narrower than ordinary user access, approved for a current role and removed when no longer needed.',
  'D8-Q06': 'People and users should have an easy route for reporting suspicious messages, account activity, access events or possible compromise before harm spreads.',
  'D8-Q07': 'Review threats such as account takeover, impersonation, deepfakes, payment redirection, credential theft and other digital methods relevant to the organisation.',
  'D8-Q08': 'Detection may combine authentication signals, behaviour analytics, alerts, device information, transaction monitoring or provider reporting to identify identity misuse.',
  'D8-Q09': 'Access reviews should confirm that sensitive and administrator permissions remain justified, current and appropriately approved.',
  'D8-Q10': 'Containment may include disabling access, protecting accounts, preserving logs, stopping transactions, notifying affected parties and investigating the cause.',
  'D9-Q01': 'Role-relevant guidance should help people recognise fraud risks in the work they actually perform and know the expected response to a concern.',
  'D9-Q02': 'Onboarding or induction is an early opportunity to explain ethical expectations, reporting routes, conflicts and the consequences of misconduct.',
  'D9-Q03': 'Messages from leaders should connect everyday choices, conflicts and speaking up with the consequences of misconduct; a policy stored on the intranet is not enough.',
  'D9-Q05': 'Use short, role-specific examples that show what a suspicious request looks like and what a person should do next.',

  'OV-D3-Q03': 'Check whether the organisation receives enough evidence or reporting to remain accountable for these supplier checks, even when the work is performed on its behalf.',
  'OV-D7-Q01': 'Check the hand-off: the external operator supplies evidence against agreed expectations, and an internal owner challenges gaps rather than accepting a tick-box update.',
  'OV-D7-Q02': 'Check that an outsourced buying process leaves an auditable trail of who evaluated the deal, declared interests and approved the price.',
  'OV-D7-Q04': 'The organisation should receive evidence or exception reporting and independently verify risky supplier-payment changes handled on its behalf.',
  'OV-D7-Q05': 'Ask what information reaches the organisation about a high-risk relationship, how exceptions are escalated and when the relationship is reconsidered.',
  'OV-D7-Q06': 'Sample reports, review notes and open actions to see whether the organisation can challenge work done outside its own team.',
  'OV-D8-Q02': 'Review the third-party platform’s fraud, dispute and account-security reports, including how those reports are escalated and used by the organisation.',
  'OV-G07': 'Use exception reports or independent checks to spot a duplicate payee, an amended account or a person who should no longer receive funds.',
});

export function customerHelpFor(nodeId: string | null | undefined): string | null {
  if (!nodeId) return null;
  const value = CUSTOMER_HELP_TEXT[nodeId];
  return typeof value === 'string' && value.trim() ? value : null;
}

export const CUSTOMER_HELP_NODE_IDS = Object.freeze(Object.keys(CUSTOMER_HELP_TEXT));
