import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

/**
 * Outer packaging for owner-review samples. The analytical pages are generated by the normal
 * report renderer first; this cover is added afterwards so the sample disclosure cannot alter the
 * scored findings, controls, narrative contract or report compositor.
 */
export const SYNTHETIC_SAMPLE_LABEL = 'SYNTHETIC DEMONSTRATION ORGANISATION';
export const SYNTHETIC_SAMPLE_TITLE = 'MK Fraud Readiness Sample | Synthetic Organisation | Not a Real Entity';
export const SYNTHETIC_SAMPLE_DISCLOSURE = 'This demonstration report was generated by the MK Fraud Readiness reporting engine from deliberately constructed synthetic assessment responses. It does not describe a real organisation. Findings reflect the information submitted through the self-assessment and do not constitute an audit, certification, assurance opinion or conclusion on the operating effectiveness of controls.';

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;

function wrapText(text: string, font: any, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    const candidate = line ? `${line} ${word}` : word;
    if (line && font.widthOfTextAtSize(candidate, size) > maxWidth) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

function drawWrapped(page: any, text: string, font: any, size: number, x: number, y: number, maxWidth: number, lineHeight: number, color: any) {
  let cursor = y;
  for (const line of wrapText(text, font, size, maxWidth)) {
    page.drawText(line, { x, y: cursor, size, font, color });
    cursor -= lineHeight;
  }
  return cursor;
}

/** Add the mandatory synthetic disclosure as a recoverable outer cover to an existing PDF. */
export async function prependSyntheticSampleCover(input: Uint8Array): Promise<Buffer> {
  const pdf = await PDFDocument.load(input);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const page = pdf.insertPage(0, [PAGE_WIDTH, PAGE_HEIGHT]);
  const navy = rgb(0.035, 0.102, 0.176);
  const brass = rgb(0.78, 0.62, 0.20);
  const cream = rgb(0.97, 0.96, 0.91);
  const muted = rgb(0.30, 0.35, 0.40);
  const left = 58;
  const width = PAGE_WIDTH - left * 2;

  page.drawRectangle({ x: 0, y: 0, width: PAGE_WIDTH, height: PAGE_HEIGHT, color: cream });
  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 210, width: PAGE_WIDTH, height: 210, color: navy });
  page.drawText('MK FRAUD INSIGHTS', { x: left, y: PAGE_HEIGHT - 72, size: 10, font: bold, color: brass });
  page.drawText(SYNTHETIC_SAMPLE_LABEL, { x: left, y: PAGE_HEIGHT - 145, size: 17, font: bold, color: rgb(1, 1, 1), maxWidth: width });

  let cursor = PAGE_HEIGHT - 280;
  cursor = drawWrapped(page, SYNTHETIC_SAMPLE_TITLE, bold, 14, left, cursor, width, 21, navy) - 34;
  page.drawRectangle({ x: left, y: cursor + 10, width: 120, height: 3, color: brass });
  cursor -= 25;
  cursor = drawWrapped(page, SYNTHETIC_SAMPLE_DISCLOSURE, regular, 10.5, left, cursor, width, 16, muted) - 28;
  cursor = drawWrapped(page, 'This cover is outer sample packaging for controlled owner review. The substantive analytical pages that follow are generated by the current MK Fraud Readiness reporting engine.', regular, 10.5, left, cursor, width, 16, muted);

  page.drawText('NON-COMMERCIAL DEMONSTRATION OUTPUT', { x: left, y: 80, size: 9, font: bold, color: navy });
  page.drawText('No order, payment, invoice, engagement or customer delivery is represented by this sample.', { x: left, y: 60, size: 8.5, font: regular, color: muted, maxWidth: width });

  pdf.setTitle(SYNTHETIC_SAMPLE_TITLE, { showInWindowTitleBar: true });
  pdf.setSubject('Controlled synthetic demonstration report. Not a real entity or commercial engagement.');
  pdf.setKeywords(['MK Fraud Readiness', 'synthetic demonstration', 'not a real entity', 'non-commercial']);
  return Buffer.from(await pdf.save({ useObjectStreams: false }));
}
