-- MK Fraud Readiness Score V1 - Phase 4 dev seed (merged)
-- Run after 0001_phase2_v1_1_schema_rls.sql in the Supabase dev project only.
--
-- Merge note: the Phase 4 v1.1 package's own version of this file only created an EMPTY
-- "methodology shell" (one active methodology_versions row with zero domains, questions,
-- response_scale or exposure_factors). That was enough to satisfy the assessments FK and
-- pass Phase 4's own tests, but it silently drops the entire approved Phase 1 methodology
-- (10 domains, 68 questions, response scale, exposure model, recommendation rules) that was
-- already generated and verified against the Technical Scoring Test Matrix during the Phase 2
-- fix pass. This merged version seeds the real content instead of a shell, is idempotent
-- (safe to re-run against the same dev project), and keeps every Phase-4-specific addition
-- (respondent_token_policy "phase":"phase4" tag, phase4_email_mode) from the original file.

do $seed$
declare
  v_methodology_id uuid;
  v_already_seeded boolean;
begin

insert into public.methodology_versions (version_code, title, status, effective_from)
values ('MFRS-V1.0', 'MK Fraud Readiness Score V1 Methodology', 'active', now())
on conflict (version_code) do update set
  title = excluded.title,
  status = excluded.status,
  effective_from = coalesce(public.methodology_versions.effective_from, excluded.effective_from),
  updated_at = now()
returning id into v_methodology_id;

select exists(
  select 1 from public.domains where methodology_version_id = v_methodology_id
) into v_already_seeded;

if not v_already_seeded then

-- Response scale (0-5, normalised 0/20/40/60/80/100)
insert into public.response_scale (methodology_version_id, response_value, label, operational_meaning, normalised_score, display_order)
values
  (v_methodology_id, 0, 'Not in place', 'The control, process or capability does not exist or is not recognised as required.', 0, 1),
  (v_methodology_id, 1, 'Initial / ad hoc', 'Some activity may occur informally or reactively, but it is not defined, owned or reliable.', 20, 2),
  (v_methodology_id, 2, 'Partially designed', 'Some elements exist, but implementation is incomplete, inconsistent or not evidenced.', 40, 3),
  (v_methodology_id, 3, 'Implemented', 'The capability is established in important areas, but may not operate consistently across the organisation.', 60, 4),
  (v_methodology_id, 4, 'Consistently operating', 'The capability is formally implemented, evidenced and regularly operating.', 80, 5),
  (v_methodology_id, 5, 'Embedded and improved', 'The capability is monitored, measured, governed and continuously improved.', 100, 6);

-- Ten fraud-readiness domains with approved weights (sum = 100)
insert into public.domains (methodology_version_id, domain_code, name, weight_pct, domain_type, is_core, sort_order)
values
  (v_methodology_id, 'D1', 'Fraud Leadership and Governance', 12, 'core', true, 1),
  (v_methodology_id, 'D2', 'Fraud Risk Identification', 12, 'core', true, 2),
  (v_methodology_id, 'D3', 'Operational Fraud Controls', 14, 'core', true, 3),
  (v_methodology_id, 'D4', 'Fraud Detection Capability', 14, 'core', true, 4),
  (v_methodology_id, 'D5', 'Fraud Incident Response', 10, 'core', true, 5),
  (v_methodology_id, 'D6', 'Whistleblowing and Reporting Culture', 6, 'support', false, 6),
  (v_methodology_id, 'D7', 'Third-Party and Supply Chain Fraud Risk', 10, 'core', true, 7),
  (v_methodology_id, 'D8', 'Digital and Identity Fraud Risk', 12, 'core', true, 8),
  (v_methodology_id, 'D9', 'Fraud Culture and Awareness', 5, 'support', false, 9),
  (v_methodology_id, 'D10', 'Continuous Improvement and Fraud Risk Monitoring', 5, 'support', false, 10);

-- 68 approved questions (Phase 1 workbook is the seed source per Blueprint section 11.1)
insert into public.questions (methodology_version_id, domain_id, question_code, prompt, help_text, weight, is_critical, is_hard_gate, n_a_allowed, n_a_rule_key, trigger_key, sort_order, active)
values
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D1'), 'D1-Q01', 'A senior executive or leadership function has clear accountability for fraud risk management.', 'Tests whether fraud risk has named leadership ownership.', 1.5, true, true, false, null, 'governance_owner_missing', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D1'), 'D1-Q02', 'Fraud risk is formally recognised within the organisation’s enterprise risk management framework.', 'Tests whether fraud is integrated into the wider risk framework.', 1.25, false, false, false, null, 'erm_integration_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D1'), 'D1-Q03', 'Fraud risks and incidents are periodically reported to senior leadership or governance committees.', 'Tests leadership visibility and reporting rhythm.', 1.25, false, false, false, null, 'fraud_reporting_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D1'), 'D1-Q04', 'Responsibility for fraud risk management is clearly distinguished from internal audit’s independent assurance role.', 'Tests whether management ownership is confused with assurance.', 1.5, true, true, false, null, 'audit_ownership_confusion', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D1'), 'D1-Q05', 'The organisation has defined policies or guidance that outline how fraud risks should be prevented, detected and managed.', 'Tests whether there is formal guidance for fraud risk management.', 1, false, false, false, null, 'policy_guidance_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D1'), 'D1-Q06', 'Leadership is informed about emerging fraud risks affecting the organisation’s sector or operating environment.', 'Tests whether leadership sees fraud as dynamic and external-facing.', 1, false, false, false, null, 'emerging_risk_visibility_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q01', 'The organisation has conducted a structured fraud risk assessment within the past two years.', 'Tests whether fraud risk has been deliberately assessed.', 1.5, true, true, false, null, 'fraud_risk_assessment_missing', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q02', 'Fraud risks have been mapped across key operational processes such as procurement, payments, refunds, claims and supplier management.', 'Tests process-level fraud-risk visibility.', 1.5, true, true, false, null, 'process_risk_mapping_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q03', 'Fraud risks are considered when introducing new products, services or digital platforms.', 'Tests whether change introduces fraud review.', 1.25, false, false, false, null, 'change_fraud_review_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q04', 'The organisation periodically reviews fraud risks in response to operational changes or new market developments.', 'Tests whether fraud-risk identification is refreshed.', 1, false, false, false, null, 'risk_refresh_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q05', 'Fraud risks related to third-party relationships, suppliers or intermediaries have been assessed.', 'Tests third-party fraud-risk identification.', 1.25, false, false, true, 'd2-q05_na_rule', 'third_party_risk_assessment_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q06', 'Emerging fraud threats affecting the organisation’s industry or sector are actively monitored.', 'Tests external fraud-threat monitoring.', 1, false, false, false, null, 'threat_monitoring_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q07', 'The organisation considers how fraud could occur through misuse of internal authority, system access or operational processes.', 'Tests insider and access-abuse risk thinking.', 1.25, false, false, false, null, 'insider_misuse_mapping_gap', 7, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D2'), 'D2-Q08', 'The organisation considers how fraud could occur through customer platforms, digital channels, loyalty programmes or service ecosystems.', 'Tests customer/digital ecosystem fraud visibility.', 1, false, false, true, 'd2-q08_na_rule', 'digital_ecosystem_risk_gap', 8, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q01', 'High-risk processes such as procurement, payments or refunds include segregation of duties between initiation, approval and reconciliation.', 'Tests core preventive control design.', 1.5, true, true, false, null, 'segregation_of_duties_gap', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q02', 'Transactions above defined financial thresholds require independent review or approval.', 'Tests threshold-based independent oversight.', 1.25, false, false, false, null, 'independent_approval_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q03', 'Supplier onboarding processes include background checks, verification of business information or due diligence.', 'Tests supplier legitimacy controls.', 1.5, true, true, false, null, 'supplier_due_diligence_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q04', 'System access rights are restricted based on job responsibilities and reviewed periodically.', 'Tests access control and periodic review.', 1.5, true, true, false, null, 'access_rights_review_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q05', 'Sensitive financial activities such as refunds, credits or manual adjustments are monitored or reviewed.', 'Tests monitoring of high-risk manual activities.', 1.25, false, false, true, 'd3-q05_na_rule', 'sensitive_activity_monitoring_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q06', 'The organisation periodically reviews operational processes to identify control weaknesses or opportunities for manipulation.', 'Tests process-control review discipline.', 1, false, false, false, null, 'process_control_review_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D3'), 'D3-Q07', 'Individuals involved in high-risk activities are subject to oversight, rotation of duties or secondary review.', 'Tests people-layer oversight in sensitive roles.', 1, false, false, true, 'd3-q07_na_rule', 'high_risk_role_oversight_gap', 7, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q01', 'The organisation monitors transactions or operational activities for unusual patterns or anomalies.', 'Tests active detection capability.', 1.5, true, true, false, null, 'anomaly_monitoring_gap', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q02', 'Exception reports highlighting unusual transactions or activities are generated and reviewed regularly.', 'Tests exception-report generation and review.', 1.25, false, false, false, null, 'exception_reporting_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q03', 'Data analytics, monitoring reports or automated rules are used to identify unusual transactions, behavioural anomalies or control exceptions.', 'Tests analytics/rules-based detection maturity.', 1.5, true, true, false, null, 'fraud_analytics_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q04', 'Detection mechanisms are updated periodically to reflect new fraud risks or emerging threats.', 'Tests detection-refresh discipline.', 1, false, false, false, null, 'detection_refresh_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q05', 'Monitoring processes cover both internal fraud risks and external fraud threats.', 'Tests breadth of monitoring coverage.', 1, false, false, false, null, 'monitoring_coverage_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q06', 'Individuals responsible for monitoring suspicious activity have clear authority to escalate concerns.', 'Tests escalation authority.', 1.25, false, false, false, null, 'escalation_authority_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D4'), 'D4-Q07', 'Internal audit or risk functions periodically review detection mechanisms to assess their effectiveness.', 'Tests independent review of detection controls.', 1, false, false, false, null, 'detection_effectiveness_review_gap', 7, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q01', 'The organisation has a documented process for responding to suspected fraud incidents.', 'Tests existence of formal response framework.', 1.5, true, true, false, null, 'incident_response_missing', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q02', 'Employees understand how and where to report suspected fraud or misconduct.', 'Tests practical reporting awareness.', 1, false, false, false, null, 'reporting_awareness_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q03', 'There are defined roles and responsibilities for managing fraud investigations.', 'Tests investigation ownership.', 1.25, false, false, false, null, 'investigation_role_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q04', 'Fraud investigations follow structured procedures that ensure fairness, confidentiality and proper documentation.', 'Tests procedural discipline in investigations.', 1.25, false, false, false, null, 'investigation_procedure_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q05', 'Evidence related to suspected fraud incidents is handled and preserved appropriately.', 'Tests evidence preservation capability.', 1.5, true, true, false, null, 'evidence_handling_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q06', 'The organisation considers engaging external specialists when incidents require forensic, legal or investigative expertise.', 'Tests escalation to specialist capability.', 1, false, false, false, null, 'specialist_escalation_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D5'), 'D5-Q07', 'Lessons learned from fraud incidents are used to improve controls and reduce future risk.', 'Tests post-incident learning.', 1.25, false, false, false, null, 'post_incident_learning_gap', 7, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D6'), 'D6-Q01', 'The organisation provides a confidential or anonymous channel for reporting suspected fraud or misconduct.', 'Tests reporting-channel availability.', 1.5, true, false, false, null, 'whistleblowing_channel_gap', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D6'), 'D6-Q02', 'Employees are aware of how to report concerns through the whistleblowing channel.', 'Tests awareness of reporting channel.', 1.25, false, false, false, null, 'whistleblowing_awareness_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D6'), 'D6-Q03', 'Reports submitted through the whistleblowing channel are reviewed and investigated independently.', 'Tests independence of report handling.', 1.25, false, false, false, null, 'whistleblowing_independence_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D6'), 'D6-Q04', 'The organisation communicates that retaliation against whistleblowers is prohibited.', 'Tests protection message.', 1, false, false, false, null, 'retaliation_protection_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D6'), 'D6-Q05', 'Whistleblowing channels are accessible to external stakeholders such as suppliers, contractors or customers.', 'Tests external stakeholder accessibility.', 1, false, false, true, 'd6-q05_na_rule', 'external_whistleblowing_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D6'), 'D6-Q06', 'Employees receive guidance or training on recognising and reporting suspicious behaviour.', 'Tests practical reporting and detection awareness.', 1, false, false, false, null, 'reporting_training_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q01', 'Suppliers, contractors or vendors are subject to background checks or due diligence before being engaged.', 'Tests third-party onboarding controls.', 1.5, true, false, false, null, 'third_party_due_diligence_gap', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q02', 'Procurement processes include safeguards designed to reduce risks of collusion or manipulation.', 'Tests procurement integrity controls.', 1.25, false, false, false, null, 'procurement_collusion_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q03', 'The organisation requires employees to disclose conflicts of interest involving suppliers or third parties.', 'Tests conflict-of-interest control.', 1.25, false, false, false, null, 'conflict_of_interest_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q04', 'Supplier payment processes include verification mechanisms to reduce risks such as invoice manipulation or vendor impersonation.', 'Tests supplier payment verification.', 1.5, true, true, false, null, 'supplier_payment_verification_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q05', 'High-risk suppliers or third-party relationships are periodically reviewed or monitored.', 'Tests ongoing supplier monitoring.', 1, false, false, true, 'd7-q05_na_rule', 'high_risk_supplier_monitoring_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q06', 'Procurement or vendor management activities are subject to oversight or periodic review.', 'Tests oversight over procurement/vendor management.', 1, false, false, false, null, 'procurement_oversight_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D7'), 'D7-Q07', 'The organisation considers fraud risks when entering partnerships, distribution arrangements or intermediary relationships.', 'Tests fraud review of partnerships/intermediaries.', 1, false, false, true, 'd7-q07_na_rule', 'intermediary_fraud_review_gap', 7, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q01', 'The organisation has processes to verify the identity of customers, users or counterparties where appropriate.', 'Tests identity verification capability.', 1.5, true, true, true, 'd8-q01_na_rule', 'identity_verification_gap', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q02', 'Systems or platforms are monitored for suspicious behaviour such as unusual login activity or account access patterns.', 'Tests account/activity monitoring.', 1.5, true, true, true, 'd8-q02_na_rule', 'suspicious_login_monitoring_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q03', 'Employees receive training on recognising phishing, social engineering and digital impersonation attempts.', 'Tests digital deception awareness.', 1.25, false, false, false, null, 'phishing_training_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q04', 'Access to sensitive systems is restricted and regularly reviewed.', 'Tests sensitive-system access governance.', 1.5, true, true, false, null, 'sensitive_system_access_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q05', 'The organisation monitors digital activity to detect potential misuse or unauthorised transactions.', 'Tests digital misuse detection.', 1.25, false, false, true, 'd8-q05_na_rule', 'digital_activity_monitoring_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q06', 'Employees and users are encouraged to report suspicious digital activity or security concerns.', 'Tests digital reporting pathway.', 1, false, false, false, null, 'digital_reporting_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q07', 'The organisation periodically reviews emerging digital fraud risks relevant to its operations or sector.', 'Tests digital fraud threat refresh.', 1, false, false, false, null, 'digital_threat_review_gap', 7, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D8'), 'D8-Q08', 'The organisation has processes to detect identity misuse, account takeover or impersonation risks affecting customers or employees.', 'Tests identity-misuse and account-takeover detection.', 1.5, true, true, true, 'd8-q08_na_rule', 'identity_misuse_detection_gap', 8, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D9'), 'D9-Q01', 'Employees receive periodic training or guidance on recognising fraud risks relevant to the organisation.', 'Tests periodic fraud awareness.', 1.25, false, false, false, null, 'fraud_training_gap', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D9'), 'D9-Q02', 'Fraud awareness is included as part of employee onboarding or induction processes.', 'Tests onboarding awareness.', 1, false, false, false, null, 'onboarding_awareness_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D9'), 'D9-Q03', 'Leadership communicates clear expectations regarding ethical conduct and fraud prevention.', 'Tests leadership tone and ethics message.', 1.25, false, false, false, null, 'leadership_ethics_message_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D9'), 'D9-Q04', 'Employees understand the consequences of engaging in fraudulent or unethical behaviour.', 'Tests consequence awareness.', 1, false, false, false, null, 'consequence_awareness_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D9'), 'D9-Q05', 'The organisation communicates real examples or scenarios to help employees recognise fraud risks.', 'Tests scenario-based fraud awareness.', 1, false, false, false, null, 'scenario_awareness_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D9'), 'D9-Q06', 'Employees feel comfortable raising concerns about suspicious behaviour without fear of negative consequences.', 'Tests cultural safety and speak-up confidence.', 1.25, false, false, false, null, 'speak_up_culture_gap', 6, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D10'), 'D10-Q01', 'The organisation periodically reviews its fraud risks and control environment.', 'Tests continuous fraud-risk review.', 1.5, true, true, false, null, 'periodic_review_missing', 1, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D10'), 'D10-Q02', 'Fraud incidents or control failures are analysed to identify underlying causes.', 'Tests root-cause analysis.', 1.25, false, false, false, null, 'root_cause_analysis_gap', 2, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D10'), 'D10-Q03', 'Lessons learned from investigations or incidents are used to improve controls and processes.', 'Tests control-improvement discipline.', 1.25, false, false, false, null, 'lessons_to_controls_gap', 3, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D10'), 'D10-Q04', 'The organisation monitors fraud trends affecting its industry or operating environment.', 'Tests trend-monitoring discipline.', 1, false, false, false, null, 'trend_monitoring_gap', 4, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D10'), 'D10-Q05', 'Fraud risks are considered when implementing new systems, products or operational changes.', 'Tests change-control fraud lens.', 1.25, false, false, false, null, 'change_control_fraud_gap', 5, true),
  (v_methodology_id, (select id from public.domains where methodology_version_id = v_methodology_id and domain_code = 'D10'), 'D10-Q06', 'Leadership periodically evaluates whether existing fraud controls remain effective.', 'Tests executive control-effectiveness review.', 1.25, false, false, false, null, 'control_effectiveness_review_gap', 6, true);

-- Eight exposure factors (max points sum = 100)
-- input_type decision: 'banded_scale_0_4' for all factors. Real decision (not a
-- placeholder): every factor is presented as a 5-point banded scale (0=none/negligible
-- through 4=extensive), mirroring the same ordinal-scale pattern already approved for
-- readiness questions, so respondents answer a consistent UI shape across the assessment.
-- Phase 5/6 may refine to a factor-specific control (e.g. a slider) without changing
-- points_awarded semantics, which are already stored independently in exposure_answers.
insert into public.exposure_factors (methodology_version_id, factor_code, name, max_points, input_type, sort_order)
values
  (v_methodology_id, 'EXP-01', 'High-risk process footprint', 25, 'banded_scale_0_4', 1),
  (v_methodology_id, 'EXP-02', 'Third-party and supplier dependency', 15, 'banded_scale_0_4', 2),
  (v_methodology_id, 'EXP-03', 'Digital channel reliance', 15, 'banded_scale_0_4', 3),
  (v_methodology_id, 'EXP-04', 'Identity and personal-data dependency', 10, 'banded_scale_0_4', 4),
  (v_methodology_id, 'EXP-05', 'Cash, stock or high-value asset handling', 10, 'banded_scale_0_4', 5),
  (v_methodology_id, 'EXP-06', 'Operational dispersion', 8, 'banded_scale_0_4', 6),
  (v_methodology_id, 'EXP-07', 'Manual intervention and exception volume', 10, 'banded_scale_0_4', 7),
  (v_methodology_id, 'EXP-08', 'Public funds, regulated payments or vulnerable stakeholders', 7, 'banded_scale_0_4', 8);

-- Applicability rules for questions marked 'Conditional' N/A in the workbook.
-- Real decision (not a placeholder): each Conditional question is gated on the exposure
-- factor whose profile most plausibly makes it inapplicable (e.g. a third-party due
-- diligence question only applies if the organisation actually has third-party exposure).
-- expression_json is a simple, evaluable condition: N/A is allowed only when the named
-- exposure factor's awarded points are 0 for this assessment. Phase 5/6 implements the
-- evaluator and may refine thresholds once real exposure_answers data exists to check
-- against; amend this seed rather than leaving the condition undefined.
insert into public.question_applicability_rules (question_id, rule_key, expression_json)
values
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D2-Q05'), 'd2-q05_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-02", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has third-party, supplier or intermediary relationships."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D2-Q08'), 'd2-q08_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-03", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has customer-facing digital channels, platforms or loyalty/service ecosystems."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D3-Q05'), 'd3-q05_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-07", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation performs manual interventions such as refunds, credits or manual adjustments."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D3-Q07'), 'd3-q07_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-01", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has high-risk operational processes with individuals in high-risk roles."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D6-Q05'), 'd6-q05_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-02", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has external stakeholders (suppliers, contractors, customers) who could use a whistleblowing channel."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D7-Q05'), 'd7-q05_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-02", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has high-risk suppliers or third-party relationships to monitor."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D7-Q07'), 'd7-q07_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-02", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation enters partnerships, distribution arrangements or intermediary relationships."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D8-Q01'), 'd8-q01_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-04", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation verifies identity of customers, users or counterparties."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D8-Q02'), 'd8-q02_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-03", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has digital platforms/systems with login or account access to monitor."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D8-Q05'), 'd8-q05_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-03", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation has digital channels where misuse or unauthorised transactions could occur."}'::jsonb),
  ((select id from public.questions where methodology_version_id = v_methodology_id and question_code = 'D8-Q08'), 'd8-q08_na_rule', '{"condition_type": "exposure_factor_threshold", "exposure_factor_code": "EXP-04", "operator": "<=", "threshold": 0, "rationale": "Only applicable if the organisation handles identity data where misuse, takeover or impersonation risk exists."}'::jsonb);

-- Recommendation trigger rules (from the approved Recommendation Triggers sheet).
-- action_30/60/90 decision: organised directly from the sheet's own action_logic column
-- into the day-30/60/90 structure the schema expects - not new methodology, just the
-- existing approved guidance broken into sequenced steps. MK/product owner may amend the
-- exact wording in Phase 6-9 content authoring without needing to invent it from scratch.
insert into public.recommendation_rules (methodology_version_id, rule_code, trigger_type, condition_json, severity, title, body, action_30, action_60, action_90, sort_order)
values
  (v_methodology_id, 'REC-01', 'workbook_trigger', '{"trigger_text": "Domain score <=39"}'::jsonb, 'Critical priority', 'Domain score <=39', 'Immediate MK review recommended; build basic ownership, controls and response foundations before relying on the score as mature.', 'Assign named executive ownership and begin an emergency baseline review of the domain''s core controls.', 'Document minimum viable controls, close any hard-gate critical gaps, and establish a basic monitoring routine.', 'Confirm baseline controls are operating consistently and schedule a follow-up MK review to re-assess maturity.', 1),
  (v_methodology_id, 'REC-02', 'workbook_trigger', '{"trigger_text": "Domain score 40-59"}'::jsonb, 'Improvement priority', 'Domain score 40-59', 'Formalise ownership, document controls, improve consistency and introduce review rhythm within 30-60 days.', 'Formalise ownership and document existing controls and processes for the domain.', 'Improve consistency of control operation across the organisation and introduce a regular review rhythm.', 'Evidence the improved controls have operated consistently for at least one full cycle and identify remaining gaps.', 2),
  (v_methodology_id, 'REC-03', 'workbook_trigger', '{"trigger_text": "Domain score 60-79"}'::jsonb, 'Strengthening priority', 'Domain score 60-79', 'Improve evidence, monitoring, escalation, analytics and cross-functional operating rhythm.', 'Review current evidence, monitoring and escalation practices for gaps.', 'Introduce or improve analytics/monitoring coverage and clarify escalation authority.', 'Establish a cross-functional operating rhythm and confirm sustained improvement with fresh evidence.', 3),
  (v_methodology_id, 'REC-04', 'workbook_trigger', '{"trigger_text": "Domain score >=80"}'::jsonb, 'Maintain and improve', 'Domain score >=80', 'Protect the capability through periodic testing, control refresh and leadership reporting.', 'Confirm current controls remain documented and owned.', 'Schedule periodic testing and a control refresh cycle.', 'Report control performance to leadership and confirm no drift has occurred.', 4),
  (v_methodology_id, 'REC-05', 'workbook_trigger', '{"trigger_text": "Any hard-gate critical control <=1"}'::jsonb, 'Maturity cap', 'Any hard-gate critical control <=1', 'Overall maturity cannot exceed Developing; include critical gap section in report.', 'Treat the failed hard-gate control as an urgent priority and assign an executive owner.', 'Implement a minimum viable version of the control and remove the immediate critical gap.', 'Confirm the control is operating and request a recalculation to determine if the cap can be lifted.', 5),
  (v_methodology_id, 'REC-06', 'workbook_trigger', '{"trigger_text": "Any hard-gate critical control =2"}'::jsonb, 'Maturity cap', 'Any hard-gate critical control =2', 'Overall maturity cannot exceed Structured; include remediation action in 30/60/90 plan.', 'Confirm what evidence is missing for the control to be considered consistently operating.', 'Close the evidence or consistency gap and document the control operation.', 'Request a recalculation once the control can be evidenced as consistently operating (response 3 or higher).', 6),
  (v_methodology_id, 'REC-07', 'workbook_trigger', '{"trigger_text": "Three or more critical controls <=2"}'::jsonb, 'Maturity cap', 'Three or more critical controls <=2', 'Overall maturity cannot exceed Developing regardless of weighted score.', 'Prioritise the critical controls with the lowest responses across all domains.', 'Close as many of the critical gaps as possible and document interim compensating measures for the rest.', 'Reduce the critical-gap count to below three and request a recalculation.', 7),
  (v_methodology_id, 'REC-08', 'workbook_trigger', '{"trigger_text": "Assessment coverage <80%"}'::jsonb, 'Invalid / incomplete', 'Assessment coverage <80%', 'Do not issue score; ask respondent to complete missing sections.', 'Identify which sections of the assessment remain incomplete.', 'Complete the outstanding sections with the correct respondent(s).', 'Resubmit the assessment once coverage reaches at least 80%.', 8),
  (v_methodology_id, 'REC-09', 'workbook_trigger', '{"trigger_text": "Assessment coverage 80-89%"}'::jsonb, 'Provisional score', 'Assessment coverage 80-89%', 'Show coverage warning and recommend MK review before report release.', 'Review the coverage warning and identify which sections were left incomplete or marked N/A.', 'Complete any sections that can reasonably be answered to raise coverage above 90%.', 'Request an MK review of the provisional score before relying on it for reporting.', 9),
  (v_methodology_id, 'REC-10', 'workbook_trigger', '{"trigger_text": "N/A rate >20%"}'::jsonb, 'Review flag', 'N/A rate >20%', 'Admin review required to ensure N/A selections are justified and not inflating the score.', 'MK reviews the N/A selections to confirm they are genuinely not applicable.', 'Where an N/A was used as a default rather than a genuine exemption, ask the respondent to provide a real answer.', 'Confirm the corrected N/A rate is below 20% before releasing a paid report.', 10);

end if;

end;
$seed$;

-- Phase-4-specific settings (kept from the original Phase 4 v1.1 dev seed)
insert into public.app_settings (setting_key, value_json)
values
  ('respondent_token_policy', '{"resume_days":14,"snapshot_days":7,"max_uses":25,"phase":"phase4"}'::jsonb),
  ('phase4_email_mode', '{"mode":"placeholder","note":"Resume link email events are recorded but not dispatched in Phase 4."}'::jsonb)
on conflict (setting_key) do update set value_json = excluded.value_json, updated_at = now();
