-- Source/cloud reconciliation (docs/safe-launch/25-source-cloud-migration-reconciliation.md):
-- this version identity was applied to jvjxlphdyzerrhwcgkup but had no corresponding file anywhere
-- in this repository's git history before this reconciliation. Recovered VERBATIM from
-- supabase_migrations.schema_migrations.statements, retrieved read-only via the Supabase MCP
-- execute_sql tool on 2026-07-25. Nothing here was invented.
--
-- Overlap note (see doc 25 for the full analysis): this migration's report_content_blocks inserts
-- use `on conflict do nothing` against the same natural key every other content-seeding migration
-- in this history uses, so restoring it alongside the already-committed
-- 0011_phase10_pdf_report_engine_additions.sql is confirmed safe -- whichever runs first "wins" a
-- given block_key, the other is silently skipped, and this was independently verified by a fresh
-- full-history replay (doc 25) rather than assumed from the ON CONFLICT clause alone.

-- MK Fraud Readiness Score V1 - Phase 10 additive migration
-- Adds the one genuinely missing column found during schema inspection, and seeds a
-- STARTER set of draft report_content_blocks so the report engine has something to
-- select from. Every block below is inserted with status='draft' - none of it is live
-- or client-facing until MK explicitly reviews and approves it (flips status to
-- 'active') via the admin content-block screen. See docs/CONTENT_BLOCKS_REVIEW_NEEDED.md.

alter table public.report_events add column if not exists metadata_json jsonb default '{}'::jsonb;

do $$
declare
  v_methodology_version_id uuid;
begin
  select id into v_methodology_version_id from public.methodology_versions where status = 'active' limit 1;
  if v_methodology_version_id is null then
    raise exception 'No active methodology version found - cannot seed report_content_blocks.';
  end if;

  insert into public.report_content_blocks
    (methodology_version_id, block_key, block_type, domain_code, maturity_band, severity, title, body, status, version_number)
  values
    (v_methodology_version_id, 'exec_summary_reactive', 'executive_summary', null, 'Reactive', null, 'There is currently no structured fraud defence in place', 'Fraud risk here is being managed the way most organisations start: informally, and mostly after something has already gone wrong. That is not a criticism - it is the honest starting point most organisations share before they build anything deliberate. The priority is not sophistication, it is foundation: naming an owner, writing down what already happens informally, and putting a basic response process in place before anything more advanced is worth attempting.', 'draft', 1),
    (v_methodology_version_id, 'exec_summary_developing', 'executive_summary', null, 'Developing', null, 'Fraud response still depends on individuals, not systems', 'Real elements of a fraud defence exist here, which is meaningfully further along than many organisations of a similar size. The gap is consistency: what protects the organisation today depends on specific people being present, informed and paying attention, rather than being embedded in how the organisation actually runs. That dependency is the single biggest source of hidden risk at this stage - not because anyone is being negligent, but because informal knowledge does not survive staff turnover, growth, or a bad week.', 'draft', 1),
    (v_methodology_version_id, 'exec_summary_structured', 'executive_summary', null, 'Structured', null, 'Real controls exist, applied with real but addressable inconsistency', 'This organisation has genuine fraud controls in place across most of what was assessed, not just policy documents describing controls that do not really operate. What separates this position from a stronger one is not the presence of controls but their consistency - how reliably they operate the same way regardless of who is on shift, how busy the team is, or how long it has been since the last incident. Closing that consistency gap is the fastest way to convert existing effort into a materially stronger position.', 'draft', 1),
    (v_methodology_version_id, 'exec_summary_strategic', 'executive_summary', null, 'Strategic', null, 'Fraud controls are structured - the remaining work is proving resilience under pressure', 'This organisation has built a genuinely mature approach to fraud risk, which places it ahead of most organisations of comparable size and complexity. From this position, the highest-value work is no longer adding controls; it is testing whether the ones in place actually hold under real pressure - a genuine incident, rapid growth, a new digital channel, or a period without the usual oversight in the room. Maturity that has not been tested is still an assumption, not yet a proven capability.', 'draft', 1),
    (v_methodology_version_id, 'exec_summary_capped', 'executive_summary', null, null, 'capped', 'A single control gap is holding back an otherwise stronger readiness position', 'Taken purely as a weighted average, this organisation''s scores would ordinarily place it in a stronger readiness category. That average is not the whole story. One or more specific, hard-gated controls scored low enough on their own to cap the overall reading, regardless of how strong the rest of the organisation looks. This is a deliberate feature of how readiness is measured here, not a scoring quirk: certain controls matter enough on their own that a serious gap in just one of them can undo the value of strength everywhere else. The qualifying control identified later in this report is exactly where leadership attention should go first - closing it is very likely to unlock the higher reading the rest of the organisation''s answers already point toward.', 'draft', 1),
    (v_methodology_version_id, 'domain_d1_structured', 'domain_narrative', 'D1', 'Structured', null, 'Fraud Leadership and Governance: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Fraud risk is often treated as an operational issue rather than a leadership responsibility, which leaves accountability fragmented across audit, compliance, operations and risk functions. Effective fraud management starts with clear ownership and genuine executive visibility, not just a policy document. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d1_strategic', 'domain_narrative', 'D1', 'Strategic', null, 'Fraud Leadership and Governance: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Fraud risk is often treated as an operational issue rather than a leadership responsibility, which leaves accountability fragmented across audit, compliance, operations and risk functions. Effective fraud management starts with clear ownership and genuine executive visibility, not just a policy document. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d2_structured', 'domain_narrative', 'D2', 'Structured', null, 'Fraud Risk Identification: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Many organisations only discover where their fraud exposure actually sits after a loss has already occurred, because risks were never systematically mapped across the processes where they actually live: procurement, payments, refunds, supplier onboarding, and digital channels. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d2_strategic', 'domain_narrative', 'D2', 'Strategic', null, 'Fraud Risk Identification: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Many organisations only discover where their fraud exposure actually sits after a loss has already occurred, because risks were never systematically mapped across the processes where they actually live: procurement, payments, refunds, supplier onboarding, and digital channels. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d3_structured', 'domain_narrative', 'D3', 'Structured', null, 'Operational Fraud Controls: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Fraud usually exploits ordinary operational gaps, not dramatic failures - missing segregation of duties, uncontrolled manual overrides, or access rights that were never reviewed after someone changed roles. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d3_strategic', 'domain_narrative', 'D3', 'Strategic', null, 'Operational Fraud Controls: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Fraud usually exploits ordinary operational gaps, not dramatic failures - missing segregation of duties, uncontrolled manual overrides, or access rights that were never reviewed after someone changed roles. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d4_structured', 'domain_narrative', 'D4', 'Structured', null, 'Fraud Detection Capability: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. A control environment that cannot detect unusual activity is relying entirely on prevention working perfectly, which it never does. Detection is what catches what prevention missed, and it needs monitoring, analytics and clear escalation authority to actually function. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d4_strategic', 'domain_narrative', 'D4', 'Strategic', null, 'Fraud Detection Capability: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. A control environment that cannot detect unusual activity is relying entirely on prevention working perfectly, which it never does. Detection is what catches what prevention missed, and it needs monitoring, analytics and clear escalation authority to actually function. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d5_structured', 'domain_narrative', 'D5', 'Structured', null, 'Fraud Incident Response: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. How an organisation responds in the first hours after a suspected fraud is discovered often matters more than the incident itself - a documented, rehearsed response process is the difference between containment and a compounding loss. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d5_strategic', 'domain_narrative', 'D5', 'Strategic', null, 'Fraud Incident Response: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. How an organisation responds in the first hours after a suspected fraud is discovered often matters more than the incident itself - a documented, rehearsed response process is the difference between containment and a compounding loss. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d6_structured', 'domain_narrative', 'D6', 'Structured', null, 'Whistleblowing and Reporting Culture: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Controls only work if people are willing to use them. A reporting channel nobody trusts, or one where retaliation is a real fear, produces silence - and silence is indistinguishable from the absence of fraud until it very obviously is not. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d6_strategic', 'domain_narrative', 'D6', 'Strategic', null, 'Whistleblowing and Reporting Culture: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Controls only work if people are willing to use them. A reporting channel nobody trusts, or one where retaliation is a real fear, produces silence - and silence is indistinguishable from the absence of fraud until it very obviously is not. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d7_structured', 'domain_narrative', 'D7', 'Structured', null, 'Third-Party and Supply Chain Fraud Risk: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Fraud risk does not stop at the organisation''s own walls. Suppliers, contractors and intermediaries introduce exposure the organisation often has less visibility into than its own internal processes, particularly around vendor impersonation and procurement collusion. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d7_strategic', 'domain_narrative', 'D7', 'Strategic', null, 'Third-Party and Supply Chain Fraud Risk: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Fraud risk does not stop at the organisation''s own walls. Suppliers, contractors and intermediaries introduce exposure the organisation often has less visibility into than its own internal processes, particularly around vendor impersonation and procurement collusion. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d8_structured', 'domain_narrative', 'D8', 'Structured', null, 'Digital and Identity Fraud Risk: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Digital channels and identity verification have become one of the fastest-moving fraud surfaces, and controls designed for a purely physical or paper-based environment do not translate automatically to online, mobile or platform-based risk. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d8_strategic', 'domain_narrative', 'D8', 'Strategic', null, 'Digital and Identity Fraud Risk: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Digital channels and identity verification have become one of the fastest-moving fraud surfaces, and controls designed for a purely physical or paper-based environment do not translate automatically to online, mobile or platform-based risk. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d9_structured', 'domain_narrative', 'D9', 'Structured', null, 'Fraud Culture and Awareness: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. A workforce that has never been taught to recognise fraud risk cannot be expected to prevent, notice or report it - awareness is a control in its own right, not a soft addition to the real ones. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d9_strategic', 'domain_narrative', 'D9', 'Strategic', null, 'Fraud Culture and Awareness: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. A workforce that has never been taught to recognise fraud risk cannot be expected to prevent, notice or report it - awareness is a control in its own right, not a soft addition to the real ones. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d10_structured', 'domain_narrative', 'D10', 'Structured', null, 'Continuous Improvement and Fraud Risk Monitoring: real controls, addressable consistency gaps', 'This domain is genuinely functioning: real controls exist and are operating across most of what was assessed here, not just described in policy. Fraud risk changes as the organisation changes. A control environment that was right two years ago and has not been reviewed since is not a mature one - it is a static one that has not yet been tested by the risks that exist today. What separates this position from a stronger one is consistency and evidence - closing the gap between what usually happens and what reliably happens every time, regardless of who is on shift or how the organisation is changing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d10_strategic', 'domain_narrative', 'D10', 'Strategic', null, 'Continuous Improvement and Fraud Risk Monitoring: a genuine strength worth protecting', 'This domain is a genuine strength, and one of the stronger readings in this assessment. Fraud risk changes as the organisation changes. A control environment that was right two years ago and has not been reviewed since is not a mature one - it is a static one that has not yet been tested by the risks that exist today. From here, the priority shifts from building controls to protecting them: periodic testing, a refresh cycle, and leadership visibility into whether performance is holding, rather than assuming a strong result today still holds tomorrow.', 'draft', 1),
    (v_methodology_version_id, 'domain_d1_reactive', 'domain_narrative', 'D1', 'Reactive', null, 'Fraud Leadership and Governance: no structured control yet', 'This domain currently has little structured control in place. What exists tends to be informal or triggered only after something has already gone wrong, rather than operating continuously. Fraud risk is often treated as an operational issue rather than a leadership responsibility, which leaves accountability fragmented across audit, compliance, operations and risk functions. This is the domain where the smallest deliberate steps - naming an owner, writing down what should happen - produce the largest immediate readiness gain.', 'draft', 1),
    (v_methodology_version_id, 'domain_d3_reactive', 'domain_narrative', 'D3', 'Reactive', null, 'Operational Fraud Controls: no structured control yet', 'This domain currently has little structured control in place. What exists tends to be informal or triggered only after something has already gone wrong, rather than operating continuously. Fraud usually exploits ordinary operational gaps, not dramatic failures - missing segregation of duties, uncontrolled manual overrides, or access rights that were never reviewed after someone changed roles. This is the domain where the smallest deliberate steps - naming an owner, writing down what should happen - produce the largest immediate readiness gain.', 'draft', 1),
    (v_methodology_version_id, 'domain_d1_developing', 'domain_narrative', 'D1', 'Developing', null, 'Fraud Leadership and Governance: real elements, inconsistently applied', 'This domain has real elements in place, but they are inconsistent - present in some parts of the organisation, or some of the time, rather than reliably embedded everywhere they need to be. Fraud risk is often treated as an operational issue rather than a leadership responsibility, which leaves accountability fragmented across audit, compliance, operations and risk functions. The next step here is formalising what already exists informally and giving it a defined review rhythm, rather than starting from nothing.', 'draft', 1),
    (v_methodology_version_id, 'domain_d8_developing', 'domain_narrative', 'D8', 'Developing', null, 'Digital and Identity Fraud Risk: real elements, inconsistently applied', 'This domain has real elements in place, but they are inconsistent - present in some parts of the organisation, or some of the time, rather than reliably embedded everywhere they need to be. Digital channels and identity verification have become one of the fastest-moving fraud surfaces, and controls designed for a purely physical or paper-based environment do not translate automatically to online, mobile or platform-based risk. The next step here is formalising what already exists informally and giving it a defined review rhythm, rather than starting from nothing.', 'draft', 1),
    (v_methodology_version_id, 'gap_d8_critical', 'gap_commentary', 'D8', null, 'critical', null, 'Identity verification is flagged as a critical, hard-gated gap. Where identity misuse can create fraud loss or harm - onboarding a customer, granting system access, approving a payment - the absence of reliable verification is not a minor process gap, it is the kind of control whose failure this methodology treats as capping the entire readiness reading, regardless of how strong every other domain looks.', 'draft', 1),
    (v_methodology_version_id, 'gap_d3_major', 'gap_commentary', 'D3', null, 'major', null, 'This control gap sits in a domain where fraud most often actually occurs in practice - day-to-day operational processes like approvals, supplier onboarding or manual overrides, rather than in more visible, higher-profile areas. Closing gaps here tends to produce disproportionate risk reduction relative to the effort involved.', 'draft', 1)
  on conflict do nothing;
end;
$$;
