-- Source/cloud reconciliation (docs/safe-launch/25-source-cloud-migration-reconciliation.md):
-- this version identity was applied to jvjxlphdyzerrhwcgkup but had no corresponding file anywhere
-- in this repository's git history before this reconciliation. Recovered VERBATIM from
-- supabase_migrations.schema_migrations.statements, retrieved read-only via the Supabase MCP
-- execute_sql tool on 2026-07-25. Nothing here was invented.
--
-- Overlap note (see doc 25): report_content_blocks inserts use `on conflict do nothing` against
-- the same natural key every other content-seeding migration in this history uses (including
-- 0011's), so restoring this alongside 0011 is confirmed safe by fresh full-history replay.
-- domain_code values below are full domain NAMES (e.g. 'Fraud Leadership and Governance'), not the
-- canonical Dn codes later migrations normalize to -- this predates that normalization
-- (20260720200442_phase_v2_content_library_domain_code_and_activation.sql), which is exactly the
-- migration that fixes rows shaped like these.

alter table public.report_events add column if not exists metadata_json jsonb default '{}'::jsonb;

do $$
declare
  v_methodology_version_id uuid;
begin
  select id into v_methodology_version_id from public.methodology_versions where status = 'active' limit 1;
  if v_methodology_version_id is null then
    raise exception 'No active methodology version found - cannot seed report_content_blocks.';
  end if;

  insert into public.report_content_blocks
    (methodology_version_id, block_key, block_type, domain_code, maturity_band, severity, title, body, status, version_number)
  values
    (v_methodology_version_id, 'exec_diagnosis_reactive', 'executive_summary', null, 'Reactive', null, 'There is no structured fraud defence in place yet', '{{organisationName}} scored {{overallScore}} out of 100, placing it in the Reactive band. In practice, this means fraud risk is currently being managed the way most organisations start: informally, and mostly noticed only after something has already gone wrong. That is the honest starting point most organisations share before they build anything deliberate - it is not a judgement on the people running the organisation today. What changes the picture fastest from here is not sophistication, it is foundation: a named owner, a written-down version of what already happens informally, and a basic response process that does not depend on any one person being in the room when something goes wrong.', 'draft', 1),
    (v_methodology_version_id, 'exec_diagnosis_developing', 'executive_summary', null, 'Developing', null, 'The organisation''s fraud defences depend on people, not systems', '{{organisationName}} scored {{overallScore}} out of 100, placing it in the Developing band. Real elements of a fraud defence already exist - which puts this organisation meaningfully ahead of many of similar size - but they are not yet consistent enough for leadership to rely on with confidence. The practical risk is dependency: what protects the organisation today depends on specific people being present, informed, and paying attention, rather than being built into how the organisation runs day to day. That dependency rarely shows up as a problem until the person it depends on is unavailable, distracted, or gone.', 'draft', 1),
    (v_methodology_version_id, 'exec_diagnosis_structured', 'executive_summary', null, 'Structured', null, 'Real controls exist - the gap is consistency, not capability', '{{organisationName}} scored {{overallScore}} out of 100, placing it in the Structured band. This is a genuinely credible position: controls exist and are operating across most of what was assessed, not just described in policy. What separates this from a stronger position is not whether the right things are in place but whether they happen the same way every time - regardless of who is on shift, how busy the team is, or how long it has been since the last incident. Closing that consistency gap, rather than adding new controls, is the fastest route to a materially stronger reading.', 'draft', 1),
    (v_methodology_version_id, 'exec_diagnosis_strategic', 'executive_summary', null, 'Strategic', null, 'Fraud controls are mature - the next test is whether they hold under pressure', '{{organisationName}} scored {{overallScore}} out of 100, placing it in the Strategic band, ahead of most organisations of comparable size and complexity. From this position, the highest-value work is no longer adding controls - it is testing whether the ones already in place hold up under real pressure: a genuine incident, rapid growth, a new digital channel, or a period without the usual oversight in the room. Maturity that has not been tested under stress is still an assumption. This report''s priority actions are built around turning that assumption into evidence.', 'draft', 1),
    (v_methodology_version_id, 'exec_diagnosis_capped', 'executive_summary', null, null, 'capped', 'A single control gap is holding back a stronger underlying position', 'Taken purely as a weighted average across all ten domains, {{organisationName}}''s responses would score {{overallScore}} out of 100 - which would ordinarily place the organisation in the {{calculatedMaturity}} readiness band. That average is not the full picture. One or more specific, non-negotiable controls scored low enough on their own to cap the final reading to {{finalMaturity}}, regardless of how strong the organisation looks everywhere else. This is a deliberate feature of how readiness is measured, not a scoring quirk: certain controls matter enough on their own that a serious gap in just one of them changes what the rest of the score is allowed to mean. The specific control responsible for this cap is identified later in this report, and closing it is very likely to unlock the higher reading the rest of the organisation''s answers already point toward.', 'draft', 1),
    (v_methodology_version_id, 'false_comfort_capped', 'false_comfort', null, null, 'capped', 'Where this organisation may look stronger than it really is', 'An overall score is an average, and averages hide two very different situations behind the same number: an organisation with genuinely consistent, moderate performance everywhere, and an organisation with strong performance almost everywhere sitting alongside one seriously weak control. {{organisationName}} is the second kind. On a simple average, the underlying responses would read as {{calculatedMaturity}}. But one of the controls behind that average is not just weak - it is one of the small number of controls this methodology treats as non-negotiable, because its failure creates a type of exposure that strength elsewhere cannot compensate for. That is precisely the kind of gap an average is built to hide, and precisely why this report leads with the capped reading rather than the flattering one.', 'draft', 1),
    (v_methodology_version_id, 'false_comfort_general', 'false_comfort', null, null, 'not_capped', 'Where a strong average can still hide a real gap', 'Even without a qualifying control failing outright, an overall score can create more confidence than the underlying picture supports. A domain sitting comfortably in the middle of the scale on average can still contain one specific control that is materially weaker than the others around it - simply outnumbered by stronger responses in the same domain. Leadership reading a domain-level score without reading the detail behind it risks treating consistent-looking numbers as consistent-looking controls, which are not always the same thing. The domain pages later in this report exist specifically to surface that distinction.', 'draft', 1),
    (v_methodology_version_id, 'leadership_attention_reactive', 'leadership_attention', null, 'Reactive', null, null, 'At this stage, the commercial risk is less about a specific fraud event and more about exposure the organisation cannot yet see coming. Without a named owner or a written baseline, the organisation has no early-warning system - the first sign of a problem is usually the loss itself, not a control catching it beforehand. For leadership, the immediate question is not ''how big is our fraud risk'' but ''who would even notice if something started going wrong right now.''', 'draft', 1),
    (v_methodology_version_id, 'leadership_attention_developing', 'leadership_attention', null, 'Developing', null, null, 'The commercial exposure here is concentration risk in people, not process. If the one or two people who currently hold this knowledge left tomorrow, how much of what protects the organisation would leave with them? That question is worth asking directly in the next leadership or board discussion, because it reframes fraud readiness from a compliance topic into a continuity and succession-planning one.', 'draft', 1),
    (v_methodology_version_id, 'leadership_attention_structured', 'leadership_attention', null, 'Structured', null, null, 'The commercial value at this stage is protecting what has already been built, not building something new. Leadership''s real question is whether the organisation can demonstrate - to a board, an insurer, a major client, or an investor performing due diligence - that these controls operate reliably, not just that they exist. Evidence and consistency, not additional controls, are what convert a good internal position into an externally defensible one.', 'draft', 1),
    (v_methodology_version_id, 'leadership_attention_strategic', 'leadership_attention', null, 'Strategic', null, null, 'At this level of maturity, the commercial value shifts from prevention to assurance: a demonstrably mature fraud control environment is itself a competitive and reputational asset, particularly with larger clients, regulators, or insurers who increasingly ask for evidence rather than assertions. The open question for leadership is whether this maturity has been genuinely tested under real pressure, or whether it has simply not yet been tested at all - those are different claims, and only one of them is provable.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_leadership_and_governance_reactive', 'domain_narrative', 'Fraud Leadership and Governance', 'Reactive', null, 'Nobody owns this until something goes wrong', 'Right now, fraud risk here has no clear home. When something happens, several people react - but before that point, no single person is accountable for whether the organisation is prepared at all. That gap is usually invisible until the moment it matters most.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_leadership_and_governance_developing', 'domain_narrative', 'Fraud Leadership and Governance', 'Developing', null, 'Ownership exists, but it isn''t backed by authority yet', 'Someone is nominally responsible for fraud risk, but the reporting rhythm, the authority to act, and the visibility to leadership are not yet consistent. Ownership without a defined forum to report into tends to quietly become a part-time responsibility, not a real one.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_leadership_and_governance_structured', 'domain_narrative', 'Fraud Leadership and Governance', 'Structured', null, 'Governance is real - the gap is proving it under audit', 'There is a genuine owner, a recognised place in the risk framework, and a reporting rhythm to leadership. What is not yet fully proven is whether that structure would hold up to external scrutiny - a board question, an insurer''s due diligence, or an audit - since structure that has never been tested externally is still, in part, an internal assumption.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_leadership_and_governance_strategic', 'domain_narrative', 'Fraud Leadership and Governance', 'Strategic', null, 'Leadership treats fraud as a strategic risk, not a compliance task', 'Fraud risk sits inside genuine governance here: named ownership, independent review, and a leadership rhythm that keeps pace with how the organisation is changing. The next test is not whether this holds internally, but whether it would satisfy an external party asking hard questions about it.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_risk_identification_structured', 'domain_narrative', 'Fraud Risk Identification', 'Structured', null, 'The organisation knows where its fraud risk actually lives', 'A structured risk assessment exists and covers the processes where fraud typically originates - procurement, payments, refunds, supplier relationships. The remaining work is keeping that map current as the organisation itself changes, rather than treating it as a one-time exercise.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_risk_identification_strategic', 'domain_narrative', 'Fraud Risk Identification', 'Strategic', null, 'Risk identification keeps pace with how the business is changing', 'This organisation doesn''t just know where its fraud risk sits today - it actively re-examines that picture as new systems, channels, and supplier relationships are introduced. That habit of re-assessment is what separates identification from a static exercise.', 'draft', 1),
    (v_methodology_version_id, 'domain_operational_fraud_controls_structured', 'domain_narrative', 'Operational Fraud Controls', 'Structured', null, 'Day-to-day processes are genuinely protected, most of the time', 'Segregation of duties, access controls, and review of sensitive manual activity are real and operating in the processes that matter most. Fraud tends to exploit the gaps between these controls rather than their absence entirely, which is exactly where consistency work should focus next.', 'draft', 1),
    (v_methodology_version_id, 'domain_operational_fraud_controls_strategic', 'domain_narrative', 'Operational Fraud Controls', 'Strategic', null, 'Operational controls have become part of how work gets done', 'These controls are not an overlay on top of normal operations - they are how the organisation actually works. That embeddedness is the hardest thing to build and the easiest thing to quietly erode during growth or restructuring, which is why periodic re-validation still matters even here.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_detection_capability_structured', 'domain_narrative', 'Fraud Detection Capability', 'Structured', null, 'The organisation can catch what prevention alone would miss', 'Monitoring, exception reporting and escalation exist and function - this organisation isn''t relying on prevention working perfectly, which it never does. What''s not yet fully proven is whether detection keeps pace as fraud methods themselves evolve, particularly digitally.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_detection_capability_strategic', 'domain_narrative', 'Fraud Detection Capability', 'Strategic', null, 'Detection here is proactive, not just reactive to alerts', 'Analytics and monitoring aren''t just catching known patterns - they''re actively updated as new fraud methods emerge. That forward-looking posture is rare, and it''s the difference between detection that ages well and detection that quietly falls behind.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_incident_response_structured', 'domain_narrative', 'Fraud Incident Response', 'Structured', null, 'A real incident would be handled, not improvised', 'A documented response process exists, roles are defined, and evidence-handling is taken seriously. The open question is whether that process has actually been rehearsed - a plan that has only ever existed on paper behaves differently under real pressure than one that has been tested.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_incident_response_strategic', 'domain_narrative', 'Fraud Incident Response', 'Strategic', null, 'Incidents make the organisation better, not just contained', 'Beyond having a response process, lessons from past incidents are genuinely fed back into stronger controls. That feedback loop is what turns incident response from a cost centre into a source of continuous improvement.', 'draft', 1),
    (v_methodology_version_id, 'domain_whistleblowing_and_reporting_culture_structured', 'domain_narrative', 'Whistleblowing and Reporting Culture', 'Structured', null, 'People have a way to speak up, and mostly trust it', 'A confidential reporting channel exists and reports are reviewed independently. Trust in a reporting channel is fragile and easily lost after a single mishandled case, which makes consistent independent review the single most important thing to protect here.', 'draft', 1),
    (v_methodology_version_id, 'domain_whistleblowing_and_reporting_culture_strategic', 'domain_narrative', 'Whistleblowing and Reporting Culture', 'Strategic', null, 'Reporting channels reach beyond just employees', 'This organisation extends its reporting culture to external stakeholders too - suppliers, customers, contractors - which meaningfully widens the surface area for catching problems early, beyond what internal reporting alone would ever surface.', 'draft', 1),
    (v_methodology_version_id, 'domain_third-party_and_supply_chain_fraud_risk_structured', 'domain_narrative', 'Third-Party and Supply Chain Fraud Risk', 'Structured', null, 'Supplier risk is managed, though visibility thins at the edges', 'Due diligence and payment-process safeguards exist for suppliers and third parties. Organisations typically have less visibility into third-party risk than their own internal processes almost by definition, so ongoing monitoring - not just onboarding checks - is where attention should concentrate.', 'draft', 1),
    (v_methodology_version_id, 'domain_third-party_and_supply_chain_fraud_risk_strategic', 'domain_narrative', 'Third-Party and Supply Chain Fraud Risk', 'Strategic', null, 'Third-party risk is monitored continuously, not just at onboarding', 'Vendor and supplier relationships are reviewed on an ongoing basis, not treated as a one-time gate at onboarding. That continuous view is what catches a trusted, long-standing supplier relationship that quietly becomes a risk over time.', 'draft', 1),
    (v_methodology_version_id, 'domain_digital_and_identity_fraud_risk_structured', 'domain_narrative', 'Digital and Identity Fraud Risk', 'Structured', null, 'Digital controls are real, but this is the fastest-moving risk area', 'Identity verification and digital monitoring are genuinely in place. This is worth flagging specifically: digital and identity fraud methods evolve faster than almost any other category assessed here, so a control that is adequate today has a shorter shelf life than in most other domains.', 'draft', 1),
    (v_methodology_version_id, 'domain_digital_and_identity_fraud_risk_strategic', 'domain_narrative', 'Digital and Identity Fraud Risk', 'Strategic', null, 'Digital and identity controls are ahead of a genuinely fast-moving threat', 'Given how quickly digital fraud methods evolve, sustaining a strong position here specifically requires more frequent review than most other domains - what counts as strong today will not automatically still be strong in twelve months.', 'draft', 1),
    (v_methodology_version_id, 'domain_digital_and_identity_fraud_risk_developing', 'domain_narrative', 'Digital and Identity Fraud Risk', 'Developing', null, 'Digital controls exist in parts, not as a system', 'Some identity and digital monitoring controls are present, but not consistently across every channel or system in use. Digital fraud risk moves quickly enough that partial coverage tends to be found by whoever is looking for the gap, rather than by internal review first.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_culture_and_awareness_structured', 'domain_narrative', 'Fraud Culture and Awareness', 'Structured', null, 'People are trained to notice, not just told policy exists', 'Fraud awareness training happens and covers real scenarios, not just abstract policy. The natural next step is measuring whether that awareness actually changes behaviour day to day, not just whether the training was delivered.', 'draft', 1),
    (v_methodology_version_id, 'domain_fraud_culture_and_awareness_strategic', 'domain_narrative', 'Fraud Culture and Awareness', 'Strategic', null, 'Awareness here is reinforced by real, current examples', 'Training uses real scenarios and lessons learned, which keeps awareness current rather than becoming a once-a-year formality. That currency is what keeps a workforce actually alert, rather than merely informed.', 'draft', 1),
    (v_methodology_version_id, 'domain_continuous_improvement_and_fraud_risk_monitoring_structured', 'domain_narrative', 'Continuous Improvement and Fraud Risk Monitoring', 'Structured', null, 'The organisation reviews itself, though not always fast enough', 'Fraud risk and controls are periodically reviewed, and incidents feed into improvement. As the organisation and the threats it faces both keep changing, the review cycle''s speed matters as much as its existence - a control environment reviewed too infrequently is functionally a static one.', 'draft', 1),
    (v_methodology_version_id, 'domain_continuous_improvement_and_fraud_risk_monitoring_strategic', 'domain_narrative', 'Continuous Improvement and Fraud Risk Monitoring', 'Strategic', null, 'This organisation treats fraud readiness as a moving target', 'Reviews happen often enough to track how both the organisation and the threat landscape are changing, rather than assuming what worked last year still works this year. That habit of continuous re-evaluation is itself a control, not just a process around one.', 'draft', 1),
    (v_methodology_version_id, 'gap_digital_identity_critical_v2', 'gap_commentary', 'Digital and Identity Fraud Risk', null, 'critical', null, 'The control responsible for capping this organisation''s overall reading is identity verification - specifically, whether the organisation reliably confirms who it is dealing with before granting access, approving a payment, or onboarding someone new. This is treated as non-negotiable because identity misuse doesn''t just create a single loss - it undermines every other control built on the assumption that the organisation knows who it''s actually dealing with.', 'draft', 1),
    (v_methodology_version_id, 'gap_operational_major_v2', 'gap_commentary', 'Operational Fraud Controls', null, 'major', null, 'This gap sits in exactly the processes where fraud most often occurs in practice - day-to-day approvals, supplier onboarding, and manual overrides - rather than in more visible, headline-risk areas. Because these processes run constantly and often outside close supervision, closing gaps here tends to produce disproportionate risk reduction relative to the effort involved.', 'draft', 1)
  on conflict do nothing;
end;
$$;
